project-includes = [
    "apps/**/*.py",
    "c2_core/**/*.py",
    "manage.py",
    "scripts/**/*.py",
]

project-excludes = [
    "apps/**/migrations/**/*.py",
    "c2_core/**/migrations/**/*.py",
]
