# Generated by Django 5.2.4 on 2026-01-04 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_rename_url_result_techstack_which_url_result_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subdomain",
            name="which_seed",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subdomains",
                to="core.seed",
            ),
        ),
    ]
