# Generated by Django 5.2.4 on 2026-01-04 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_subdomain_which_seed"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubdomainSeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name="subdomain",
            name="core_subdom_which_s_e6fc4a_idx",
        ),
        migrations.AlterUniqueTogether(
            name="subdomain",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="historicalsubdomain",
            name="which_seed",
        ),
        migrations.AddField(
            model_name="subdomainseed",
            name="seed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_links",
                to="core.seed",
            ),
        ),
        migrations.AddField(
            model_name="subdomainseed",
            name="subdomain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seed_links",
                to="core.subdomain",
            ),
        ),
        migrations.RemoveField(
            model_name="subdomain",
            name="which_seed",
        ),
        migrations.AlterUniqueTogether(
            name="subdomainseed",
            unique_together={("subdomain", "seed")},
        ),
        migrations.AddField(
            model_name="subdomain",
            name="which_seed",
            field=models.ManyToManyField(
                related_name="subdomains", through="core.SubdomainSeed", to="core.seed"
            ),
        ),
    ]
