# Generated by Django 5.2.4 on 2026-01-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_nucleiscan_completed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalurlresult",
            name="content_fetch_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("SUCCESS_FETCHED", "SUCCESS_FETCHED"),
                    ("FAILED_NO_CONTENT", "FAILED_NO_CONTENT"),
                    ("FAILED_NETWORK_ERROR", "FAILED_NETWORK_ERROR"),
                    ("FAILED_BLOCKED", "FAILED_BLOCKED"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="urlresult",
            name="content_fetch_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("SUCCESS_FETCHED", "SUCCESS_FETCHED"),
                    ("FAILED_NO_CONTENT", "FAILED_NO_CONTENT"),
                    ("FAILED_NETWORK_ERROR", "FAILED_NETWORK_ERROR"),
                    ("FAILED_BLOCKED", "FAILED_BLOCKED"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
