"""
Django settings for c2_core project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os  # 導入 os 模塊，用於操作系統相關功能
from pathlib import Path  # 導入 Path 模塊，用於處理文件路徑


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent  # 定義項目根目錄的路徑


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-=kr5uz%vc5zo$2ex*^hb2uw&+2odbk2r1sp)l6s@-ess_qgume"  # Django 項目的密鑰，用於加密簽名，生產環境中應保密

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # 開啟調試模式，開發環境使用，生產環境應設為 False

ALLOWED_HOSTS = []  # 允許訪問 Django 應用的主機名列表，開發環境通常為空


# Application definition

INSTALLED_APPS = [  # 註冊 Django 項目中使用的應用程序列表
    "django.contrib.admin",  # Django 管理後台應用
    "django.contrib.auth",  # 用戶認證系統
    "django.contrib.contenttypes",  # 內容類型框架
    "django.contrib.sessions",  # 會話管理系統
    "django.contrib.messages",  # 消息框架
    "django.contrib.staticfiles",  # 靜態文件管理
    "rest_framework",  # Django REST framework 應用
    "rest_framework.authtoken",  # DRF 的 Token 認證應用
    # 操！就是這裡！把你自己的核心 App 加進來！
    "c2_core",  # <--- 加上這行！ # 核心應用程序
    # 你的 Apps
    "apps.targets",  # 自定義應用：目標管理
    "apps.nmap_scanner",  # 自定義應用：Nmap 掃描器
    "apps.flaresolverr",  # 自定義應用：FlareSolverr 代理集成
    "apps.core",  # 自定義應用：核心應用
    # 你未來還要加 celery, redis 相關的 app 等等
    "corsheaders",  # 處理跨域請求的第三方應用
    "apps.subfinder",
    "django_extensions",
    "apps.scheduler",
    "django_celery_beat",
    "apps.analyze_ai",  # 操！把指揮中心加在其他 app 前面，或者就加在列表裡
    "apps.nuclei_scanner",
    "apps.api_keys",
]
MIDDLEWARE = [  # 中間件列表，處理請求和響應的層次
    "corsheaders.middleware.CorsMiddleware",  # CORS 中間件，處理跨域請求
    "django.middleware.security.SecurityMiddleware",  # 安全相關中間件，提供各種安全保護
    "django.contrib.sessions.middleware.SessionMiddleware",  # 會話中間件，處理用戶會話
    "django.middleware.common.CommonMiddleware",  # 通用中間件，處理一些常見請求行為
    "django.middleware.csrf.CsrfViewMiddleware",  # CSRF 保護中間件
    "django.contrib.auth.middleware.AuthenticationMiddleware",  # 認證中間件，將用戶綁定到請求
    "django.contrib.messages.middleware.MessageMiddleware",  # 消息中間件，處理消息框架
    "django.middleware.clickjacking.XFrameOptionsMiddleware",  # 點擊劫持保護中間件
]
CORS_ALLOWED_ORIGINS = [  # 允許進行跨域請求的來源列表
    "http://localhost:5173",  # 你的前端應用程式跑的地址！ # 允許本地開發前端應用訪問
    "http://127.0.0.1:5173",  # 有時候瀏覽器會用 127.0.0.1，都加進來！ # 允許本地開發前端應用訪問
    # 如果你未來部署到其他域名，也要加在這裡
    # "https://your.frontend.domain.com",
]
CORS_ALLOW_METHODS = [  # 允許進行跨域請求的 HTTP 方法列表
    "DELETE",  # 允許 DELETE 方法
    "GET",  # 允許 GET 方法
    "OPTIONS",  # 允許 OPTIONS 方法
    "PATCH",  # 允許 PATCH 方法
    "POST",  # 允許 POST 方法
    "PUT",  # 允許 PUT 方法
]
CORS_ALLOW_CREDENTIALS = (
    True  # <--- 加上這行！ # 允許在跨域請求中發送憑證 (如 cookies, HTTP 認證)
)

# 如果需要允許特定的 HTTP 頭 (Content-Type, Authorization...)
CORS_ALLOW_HEADERS = [  # 允許在跨域請求中使用的 HTTP 頭列表
    "accept",  # 允許 Accept 頭
    "accept-encoding",  # 允許 Accept-Encoding 頭
    "authorization",  # 允許 Authorization 頭
    "content-type",  # 允許 Content-Type 頭
    "dnt",  # 允許 DNT (Do Not Track) 頭
    "origin",  # 允許 Origin 頭
    "user-agent",  # 允許 User-Agent 頭
    "x-csrftoken",  # 允許 X-CSRFToken 頭
    "x-requested-with",  # 允許 X-Requested-With 頭
]
ROOT_URLCONF = "c2_core.urls"  # 指定 Django 項目的根 URL 配置模塊

TEMPLATES = [  # Django 模板引擎配置
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",  # 使用 Django 內置模板引擎
        "DIRS": [],  # 模板文件查找目錄列表
        "APP_DIRS": True,  # 允許 Django 在每個應用的 'templates' 目錄中查找模板
        "OPTIONS": {  # 模板引擎的其他選項
            "context_processors": [  # 上下文處理器列表，將額外數據添加到模板上下文
                "django.template.context_processors.request",  # 將請求對象添加到上下文
                "django.contrib.auth.context_processors.auth",  # 將用戶相關數據添加到上下文
                "django.contrib.messages.context_processors.messages",  # 將消息添加到上下文
            ],
        },
    },
]

WSGI_APPLICATION = "c2_core.wsgi.application"  # 指定 WSGI 應用程序入口點


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {  # 數據庫配置
    "default": {  # 默認數據庫
        # 'ENGINE': 告訴 Django 我們用的是 PostgreSQL
        "ENGINE": "django.db.backends.postgresql",  # 指定使用 PostgreSQL 作為數據庫引擎
        # 'NAME': 對應你舊的 POSTGRES_DB
        "NAME": os.environ.get("POSTGRES_DB")
        or "mydb",  # 數據庫名稱，從環境變量獲取或使用默認值
        # 'USER': 對應你舊的 POSTGRES_USER
        "USER": os.environ.get("POSTGRES_USER")
        or "myuser",  # 數據庫用戶名，從環境變量獲取或使用默認值
        # 'PASSWORD': 對應你舊的 POSTGRES_PASSWORD
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD")
        or "secret",  # 數據庫密碼，從環境變量獲取或使用默認值
        # 'HOST': 對應你舊的 POSTGRES_HOST
        "HOST": os.environ.get("POSTGRES_HOST")
        or "localhost",  # 數據庫主機地址，從環境變量獲取或使用默認值
        # 'PORT': 對應你舊的 POSTGRES_PORT
        "PORT": os.environ.get("POSTGRES_PORT")
        or "5432",  # 數據庫端口，從環境變量獲取或使用默認值
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [  # 密碼驗證器列表，用於增強密碼安全性
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",  # 防止與用戶屬性相似的密碼
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",  # 要求密碼達到最小長度
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",  # 防止使用常見密碼
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",  # 要求密碼不能全為數字
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"  # 網站的默認語言代碼

TIME_ZONE = "UTC"  # 網站的默認時區

USE_I18N = True  # 是否啟用 Django 的國際化系統

USE_TZ = True  # 是否啟用時區支持


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"  # 靜態文件的 URL 前綴

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"  # 模型中自動創建主鍵的默認字段類型
CELERY_BROKER_URL = "redis://localhost:6379/0"  # Celery 消息代理的 URL (這裡使用 Redis)

# 任務結果儲存地址 (也可以用 Redis)
CELERY_RESULT_BACKEND = (
    "redis://localhost:6379/0"  # Celery 任務結果後端 URL (這裡使用 Redis)
)

# 任務結果的序列化格式
CELERY_RESULT_SERIALIZER = "json"  # Celery 任務結果的序列化格式設為 JSON

# 任務接受的內容類型
CELERY_ACCEPT_CONTENT = ["json"]  # Celery 接受的內容類型設為 JSON

# 任務序列化格式
CELERY_TASK_SERIALIZER = "json"  # Celery 任務的序列化格式設為 JSON

# 時區設定
CELERY_TIMEZONE = "UTC"  # Celery 的時區設定為 UTC
# 在 settings.py 的末尾加上
REST_FRAMEWORK = {  # Django REST framework 配置
    "DEFAULT_AUTHENTICATION_CLASSES": [  # 默認的認證類列表
        # 媽的，把 SessionAuthentication 換成下面這個！
        "rest_framework.authentication.TokenAuthentication",  # 使用 Token 認證作為默認認證方式
    ],
    "DEFAULT_PERMISSION_CLASSES": [  # 默認的權限類列表
        # 預設情況下，所有接口都需要登錄才能訪問
        "rest_framework.permissions.IsAuthenticated",  # 預設所有接口需要用戶登錄才能訪問
    ],
}
CELERY_IMPORTS = (
    "apps.nmap_scanner.tasks",
    "apps.flaresolverr.tasks.spider",
    "apps.get_all_url.tasks",
    "apps.subfinder.tasks",
    "apps.analyze_ai.tasks",
    "apps.nuclei_scanner.tasks",
    "apps.scheduler.tasks",
)  # <--- 加上這行！用元組，即使只有一個也加逗號 # 指定 Celery 啟動時需要導入的模塊，包含 Celery 任務
API_BASE_URL = "http://127.0.0.1:8000"
LOG_DIR = BASE_DIR / "c2_core" / "logs"
LOG_DIR.mkdir(parents=True, exist_ok=True)
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "rich": {"datefmt": "[%X]"},
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {asctime} {message}",
            "style": "{",
        },
    },
    "handlers": {
        # 1. 螢幕顯示 (Rich)
        "console": {
            "class": "rich.logging.RichHandler",
            "formatter": "rich",
            "level": "INFO",
            "rich_tracebacks": True,
            "tracebacks_show_locals": True,
        },
        # 2. 一般日誌 (app.txt)
        "app_file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIR / "app.log",
            "maxBytes": 1024 * 1024 * 10,
            "backupCount": 5,
            "formatter": "verbose",
            "encoding": "utf-8",
        },
        # 3. 錯誤日誌 (error.txt)
        "error_file": {
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIR / "error.log",
            "maxBytes": 1024 * 1024 * 10,
            "backupCount": 10,
            "formatter": "verbose",
            "encoding": "utf-8",
        },
    },
    "loggers": {
        # 根日誌記錄器：所有沒被接管的日誌都會走這路
        "": {
            "handlers": ["console", "app_file", "error_file"],  # <--- 把這三個都接上！
            "level": "INFO",
        },
        # 你的核心業務代碼
        "c2_core": {
            "handlers": ["console", "app_file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "flaresolverr": {
            "handlers": ["console", "app_file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "targets": {
            "handlers": ["console", "app_file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "scheduler": {
            "handlers": ["console", "app_file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "nmap_scanner": {
            "handlers": ["console", "app_file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "analyze_ai": {
            "handlers": ["console", "app_file", "error_file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "nuclei_scanner": {
            "handlers": ["console", "app_file", "error_file"],
            "level": "DEBUG",
            "propagate": False,
        },
        # 資料庫日誌
        "django.db.backends": {
            "handlers": ["console", "app_file", "error_file"],
            "level": "WARNING",
            "propagate": False,
        },
        # Uvicorn 訪問日誌
        "uvicorn": {
            "handlers": ["console", "app_file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
