"""
apps/auto/cai/ai_analysis_tools.py

⚠️  DEPRECATED ⚠️
此模組已被取代，請勿在此新增工具。

/analyze_ai/* API 端點現在由 `api_tool_factory` 自動包含。
"""

import warnings
warnings.warn(
    "apps.auto.cai.ai_analysis_tools is deprecated. "
    "analyze_ai API tools are now auto-generated by api_tool_factory. "
    "Do not add new tools here.",
    DeprecationWarning,
    stacklevel=2,
)


import logging
from typing import List, Dict, Any
from .core.tool import function_tool
from apps.analyze_ai.tasks import (
    trigger_ai_analysis_for_ips,
    trigger_ai_analysis_for_subdomains,
    trigger_ai_analysis_for_urls
)

logger = logging.getLogger(__name__)

@function_tool
def analyze_ips(ip_ids: List[int]) -> str:
    """
    對一組 IP 地址觸發 AI 安全分析。
    
    參數:
        ip_ids: 要分析的 IP 資料庫 ID 列表。
        
    返回:
        任務派發狀態訊息。
    """
    try:
        trigger_ai_analysis_for_ips.delay(ip_ids)
        return f"已成功為 {len(ip_ids)} 個 IP 派發 AI 分析任務。"
    except Exception as e:
        logger.error(f"派發 IP 分析任務失敗: {e}")
        return f"錯誤: {str(e)}"

@function_tool
def analyze_subdomains(subdomain_ids: List[int]) -> str:
    """
    對一組子域名觸發 AI 安全分析。
    
    參數:
        subdomain_ids: 要分析的子域名資料庫 ID 列表。
        
    返回:
        任務派發狀態訊息。
    """
    try:
        trigger_ai_analysis_for_subdomains.delay(subdomain_ids)
        return f"已成功為 {len(subdomain_ids)} 個子域名派發 AI 分析任務。"
    except Exception as e:
        logger.error(f"派發子域名分析任務失敗: {e}")
        return f"錯誤: {str(e)}"

@function_tool
def analyze_urls(url_ids: List[int]) -> str:
    """
    對一組 URL 觸發 AI 安全分析。
    
    參數:
        url_ids: 要分析的 URL 資料庫 ID 列表。
        
    返回:
        任務派發狀態訊息。
    """
    try:
        trigger_ai_analysis_for_urls.delay(url_ids)
        return f"已成功為 {len(url_ids)} 個 URL 派發 AI 分析任務。"
    except Exception as e:
        logger.error(f"派發 URL 分析任務失敗: {e}")
        return f"錯誤: {str(e)}"
