"""
apps/auto/cai/platform_tools.py

⚠️  DEPRECATED ⚠️
此模組已被取代，請勿在此新增工具。
平台 API 工具現在由 `apps.auto.cai.core.api_tool_factory.build_tools_from_openapi()` 自動生成。

保留此檔案是為了不破壞尚在外部匯入讓筆的標準 import。
待確認沒有其他模組依賴後，可安全刪除此檔案。
"""

import warnings
warnings.warn(
    "apps.auto.cai.platform_tools is deprecated. "
    "API tools are now auto-generated by api_tool_factory.build_tools_from_openapi(). "
    "Do not add new tools here.",
    DeprecationWarning,
    stacklevel=2,
)


import json
import logging
import requests
from typing import List, Dict, Any, Optional

from django.conf import settings
from apps.analyze_ai.tasks.common import (
    get_graphql_client,
    GET_SUBDOMAINS_DETAILS_QUERY,
    GET_IPS_DETAILS_QUERY,
    fetch_subdomain_data_for_batch,
    fetch_ip_data_for_batch
)
from apps.auto.cai.core.tool import function_tool

logger = logging.getLogger(__name__)

# REST API 調用的基礎 URL（本地 Django 伺服器）
API_BASE_URL = getattr(settings, "INTERNAL_API_BASE_URL", "http://127.0.0.1:8000/api")

# =============================================================================
# 1. 資產發現工具 (GraphQL)
# =============================================================================

@function_tool
def get_subdomains_info(subdomain_ids: List[int]) -> str:
    """
    使用 GraphQL 獲取特定子域名的詳細信息。
    包括技術棧、CDN/WAF 信息和 DNS 記錄。
    
    參數:
        subdomain_ids: 子域名資料庫 ID 列表。
        
    返回:
        包含子域名詳情的 JSON 字符串。
    """
    try:
        data = fetch_subdomain_data_for_batch(subdomain_ids)
        return json.dumps(data, indent=2, ensure_ascii=False)
    except Exception as e:
        logger.error(f"Error fetching subdomain info: {e}")
        return f"Error: {str(e)}"

@function_tool
def get_ips_info(ip_ids: List[int]) -> str:
    """
    使用 GraphQL 獲取特定 IP 的詳細信息。
    包括開放端口、服務和相關子域名。
    
    參數:
        ip_ids: IP 資料庫 ID 列表。
        
    返回:
        包含 IP 詳情的 JSON 字符串。
    """
    try:
        data = fetch_ip_data_for_batch(ip_ids)
        return json.dumps(data, indent=2, ensure_ascii=False)
    except Exception as e:
        logger.error(f"Error fetching IP info: {e}")
        return f"Error: {str(e)}"

# =============================================================================
# 2. 掃描器觸發工具 (REST API)
# =============================================================================

@function_tool
def trigger_subfinder(seed_id: int) -> str:
    """
    對特定的種子 ID (Seed ID) 觸發 Subfinder 偵察掃描。
    
    參數:
        seed_id: 要掃描的 DOMAIN 種子 ID。
        
    返回:
        來自 API 的響應。
    """
    url = f"{API_BASE_URL}/subfinder/start_subfinder"
    payload = {"seed_id": seed_id}
    try:
        response = requests.post(url, json=payload, timeout=10)
        response.raise_for_status()
        return json.dumps(response.json(), indent=2)
    except requests.RequestException as e:
        logger.error(f"Error triggering Subfinder: {e}")
        return f"Error triggering Subfinder: {str(e)}"

@function_tool
def trigger_nuclei_scan(asset_type: str, asset_ids: List[int], tags: Optional[List[str]] = None) -> str:
    """
    觸發 Nuclei 漏洞或技術掃描。
    
    參數:
        asset_type: 資產類型 ('subdomains', 'ips', 'urls', 'subs_tech', 'urls_tech')。
        asset_ids: 要掃描的資料庫 ID 列表。
        tags: 選用的 Nuclei 標籤 (例如：['cves', 'exposure'])。
        
    返回:
        來自 API 的響應。
    """
    endpoint_map = {
        "subdomains": "/nuclei_scanner/subdomains",
        "ips": "/nuclei_scanner/ips",
        "urls": "/nuclei_scanner/urls",
        "subs_tech": "/nuclei_scanner/subs_tech",
        "urls_tech": "/nuclei_scanner/urls_tech"
    }
    
    if asset_type not in endpoint_map:
        return f"Error: Invalid asset_type '{asset_type}'. Valid types: {list(endpoint_map.keys())}"
    
    url = f"{API_BASE_URL}{endpoint_map[asset_type]}"
    payload = {"ids": asset_ids}
    if tags:
        payload["tags"] = tags
        
    try:
        response = requests.post(url, json=payload, timeout=10)
        response.raise_for_status()
        return json.dumps(response.json(), indent=2)
    except requests.RequestException as e:
        logger.error(f"Error triggering Nuclei scan: {e}")
        return f"Error triggering Nuclei scan: {str(e)}"
