# Generated by Django 5.2.4 on 2026-03-07 12:52

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtractedJS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="抽取到的 JS 原始內容。")),
                (
                    "content_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_analyzed",
                    models.BooleanField(
                        default=False,
                        help_text="是否已完成針對此 JS block 的分析（抽 endpoint/json 等）。",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ipv4",
                    models.GenericIPAddressField(
                        blank=True, db_index=True, null=True, protocol="ipv4"
                    ),
                ),
                (
                    "ipv6",
                    models.GenericIPAddressField(
                        blank=True, null=True, protocol="ipv6"
                    ),
                ),
                (
                    "last_scan_type",
                    models.CharField(
                        blank=True,
                        help_text="掃描類型 (e.g. NmapScan)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "last_scan_id",
                    models.IntegerField(blank=True, help_text="掃描 ID", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JavaScriptFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "src",
                    models.URLField(
                        db_index=True,
                        help_text="JS 檔案 URL（script src）。若為 inline/無 src 可為空。",
                        max_length=2048,
                        null=True,
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待下載"),
                            ("DOWNLOADED", "已下載"),
                            ("ANALYZED", "已分析"),
                            ("FAILED", "失敗"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="下載/分析流程狀態。",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="JS 檔案內容（下載成功後保存）。",
                        null=True,
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(default=0, help_text="下載失敗重試次數。"),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True,
                        help_text="最後一次失敗原因（exception/message）。",
                        null=True,
                    ),
                ),
                (
                    "is_analyzed",
                    models.BooleanField(
                        default=False,
                        help_text="是否已完成靜態分析/抽取（endpoint/param/json 等）。",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NmapScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待處理"),
                            ("RUNNING", "運行中"),
                            ("COMPLETED", "已完成"),
                            ("FAILED", "失敗"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("nmap_args", models.TextField()),
                ("nmap_output", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Seed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="種子內容，如 google.com", max_length=512
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DOMAIN", "Root Domain (e.g., google.com)"),
                            ("IP_RANGE", "IP/CIDR (e.g., 192.168.1.0/24)"),
                            ("URL", "Specific URL (e.g., https://api.site.com)"),
                        ],
                        default="DOMAIN",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="是否啟用此種子進行掃描"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="專案名稱，如 'Google'", max_length=255, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="專案描述與備註", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalSubdomain",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "sources_text",
                    models.TextField(
                        blank=True, help_text="Comma-separated list of sources"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_resolvable", models.BooleanField(default=True)),
                ("is_tech_analyzed", models.BooleanField(default=False)),
                ("first_seen", models.DateTimeField(blank=True, editable=False)),
                ("last_seen", models.DateTimeField(blank=True, editable=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("dns_records", models.JSONField(blank=True, null=True)),
                ("cname", models.TextField(blank=True, null=True)),
                ("is_cdn", models.BooleanField(default=False)),
                ("is_waf", models.BooleanField(default=False)),
                ("waf_name", models.TextField(null=True)),
                ("cdn_name", models.TextField(null=True)),
                (
                    "last_scan_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("last_scan_id", models.IntegerField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.target",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical subdomain",
                "verbose_name_plural": "historical subdomains",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPort",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("port_number", models.IntegerField(db_index=True)),
                ("protocol", models.CharField(max_length=10)),
                ("state", models.CharField(db_index=True, max_length=20)),
                (
                    "service_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "service_version",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("first_seen", models.DateTimeField(blank=True, editable=False)),
                ("last_seen", models.DateTimeField(blank=True, editable=False)),
                (
                    "last_scan_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("last_scan_id", models.IntegerField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ip",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.ip",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical port",
                "verbose_name_plural": "historical ports",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="IPAIAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="如果任務失敗，記錄錯誤信息", null=True
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="AI 生成的關於此 IP 的一句話總結",
                        null=True,
                    ),
                ),
                (
                    "inferred_purpose",
                    models.TextField(
                        blank=True,
                        help_text="推斷的服務器用途 (e.g., Web Server, Mail Server, C2)",
                        null=True,
                    ),
                ),
                (
                    "risk_score",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="綜合風險評分 (0-100)", null=True
                    ),
                ),
                (
                    "potential_vulnerabilities",
                    models.JSONField(
                        blank=True,
                        help_text="基於開放端口和服務推斷的潛在漏洞列表",
                        null=True,
                    ),
                ),
                (
                    "recommended_actions",
                    models.JSONField(
                        blank=True, help_text="建議採取的後續行動列表", null=True
                    ),
                ),
                (
                    "command_actions",
                    models.JSONField(
                        blank=True, help_text="建議採取的後續命令列表", null=True
                    ),
                ),
                (
                    "port_analysis_summary",
                    models.TextField(
                        blank=True, help_text="對開放端口和服務的綜合分析", null=True
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True,
                        help_text="AI Provider 返回的完整原始 JSON 數據",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_analyses",
                        to="core.ip",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JSONObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        blank=True,
                        help_text="此 JSON 節點的風險/重要性分數（可選，依你的分析器而定）。",
                        null=True,
                    ),
                ),
                (
                    "path",
                    models.TextField(
                        blank=True,
                        help_text="節點在 JSON 中的路徑（例如 $.a.b[0].c）。",
                        null=True,
                    ),
                ),
                (
                    "depth",
                    models.IntegerField(
                        blank=True,
                        help_text="節點深度（root=0 或 1 依你的實作）。",
                        null=True,
                    ),
                ),
                (
                    "key",
                    models.TextField(
                        blank=True, help_text="節點 key（若為 object）。", null=True
                    ),
                ),
                (
                    "struct",
                    models.TextField(
                        blank=True,
                        help_text="節點型別/結構描述（例如 object/array/string）。",
                        null=True,
                    ),
                ),
                (
                    "val",
                    models.TextField(
                        blank=True,
                        help_text="節點值（可能為截斷後的字串表示）。",
                        null=True,
                    ),
                ),
                (
                    "which_extracted_js",
                    models.ForeignKey(
                        blank=True,
                        help_text="若 JSON 來源為 inline JS block，指向 ExtractedJS。",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="json_objects",
                        to="core.extractedjs",
                    ),
                ),
                (
                    "which_javascript_file",
                    models.ForeignKey(
                        blank=True,
                        help_text="若 JSON 來源為外部 JS 檔案，指向 JavaScriptFile。",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="json_objects",
                        to="core.javascriptfile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ip",
            name="discovered_by_scans",
            field=models.ManyToManyField(
                blank=True, related_name="ips_discovered", to="core.nmapscan"
            ),
        ),
        migrations.AddField(
            model_name="nmapscan",
            name="which_seed",
            field=models.ManyToManyField(
                blank=True, related_name="nmap_scans", to="core.seed"
            ),
        ),
        migrations.AddField(
            model_name="ip",
            name="which_seed",
            field=models.ManyToManyField(related_name="ips", to="core.seed"),
        ),
        migrations.CreateModel(
            name="Subdomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "sources_text",
                    models.TextField(
                        blank=True, help_text="Comma-separated list of sources"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_resolvable", models.BooleanField(default=True)),
                ("is_tech_analyzed", models.BooleanField(default=False)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("dns_records", models.JSONField(blank=True, null=True)),
                ("cname", models.TextField(blank=True, null=True)),
                ("is_cdn", models.BooleanField(default=False)),
                ("is_waf", models.BooleanField(default=False)),
                ("waf_name", models.TextField(null=True)),
                ("cdn_name", models.TextField(null=True)),
                (
                    "last_scan_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("last_scan_id", models.IntegerField(blank=True, null=True)),
                (
                    "ips",
                    models.ManyToManyField(
                        blank=True, related_name="subdomains", to="core.ip"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubBrute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待處理"),
                            ("RUNNING", "運行中"),
                            ("COMPLETED", "已完成"),
                            ("FAILED", "失敗"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("added_count", models.IntegerField(default=0, help_text="新發現數量")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "which_sub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="SubBrute",
                        to="core.subdomain",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalSubdomain_ips",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.historicalsubdomain",
                    ),
                ),
                (
                    "ip",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.ip",
                    ),
                ),
                (
                    "subdomain",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.subdomain",
                    ),
                ),
            ],
            options={
                "verbose_name": "HistoricalSubdomain_ips",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="SubdomainAIAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="如果任務失敗，記錄錯誤信息", null=True
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="AI 生成的關於此子域名用途和重要性的總結",
                        null=True,
                    ),
                ),
                (
                    "inferred_purpose",
                    models.TextField(
                        blank=True,
                        help_text="推斷的子域名用途 (e.g., Main Website, API Endpoint, Staging Environment, Blog)",
                        null=True,
                    ),
                ),
                (
                    "risk_score",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="綜合風險評分 (0-100)", null=True
                    ),
                ),
                (
                    "potential_vulnerabilities",
                    models.JSONField(
                        blank=True,
                        help_text="基於其屬性推斷的潛在攻擊向量/漏洞列表",
                        null=True,
                    ),
                ),
                (
                    "recommended_actions",
                    models.JSONField(
                        blank=True, help_text="建議採取的後續行動列表", null=True
                    ),
                ),
                (
                    "command_actions",
                    models.JSONField(
                        blank=True, help_text="建議採取的後續命令列表", null=True
                    ),
                ),
                (
                    "business_impact",
                    models.CharField(
                        blank=True,
                        help_text="推斷的業務重要性 (e.g., Critical, High, Medium, Low)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "tech_stack_summary",
                    models.TextField(
                        blank=True,
                        help_text="對其技術棧的風險分析 (e.g., 'Runs outdated WordPress')",
                        null=True,
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True,
                        help_text="AI Provider 返回的完整原始 JSON 數據",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subdomain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_analyses",
                        to="core.subdomain",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubdomainSeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "seed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_links",
                        to="core.seed",
                    ),
                ),
                (
                    "subdomain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seed_links",
                        to="core.subdomain",
                    ),
                ),
            ],
            options={
                "unique_together": {("subdomain", "seed")},
            },
        ),
        migrations.AddField(
            model_name="subdomain",
            name="which_seed",
            field=models.ManyToManyField(
                related_name="subdomains", through="core.SubdomainSeed", to="core.seed"
            ),
        ),
        migrations.CreateModel(
            name="SubfinderScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待處理"),
                            ("RUNNING", "運行中"),
                            ("COMPLETED", "已完成"),
                            ("FAILED", "失敗"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("added_count", models.IntegerField(default=0, help_text="新發現數量")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "which_seed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfinder_scans",
                        to="core.seed",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="subdomain",
            name="discovered_by_scans",
            field=models.ManyToManyField(
                blank=True, related_name="updated_subdomains", to="core.subfinderscan"
            ),
        ),
        migrations.AddField(
            model_name="subdomain",
            name="target",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subdomains",
                to="core.target",
            ),
        ),
        migrations.AddField(
            model_name="seed",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seeds",
                to="core.target",
            ),
        ),
        migrations.AddField(
            model_name="ip",
            name="target",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ips",
                to="core.target",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalURLResult",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "discovery_source",
                    models.CharField(
                        choices=[
                            ("SCAN", "Initial Scan"),
                            ("CRAWL_html", "Web Crawler (HTML)"),
                            ("JS_EXT", "JS/Xurls Extraction"),
                            ("BRUTE", "Directory Brute Force"),
                            ("API", "External API Discovery"),
                        ],
                        default="SCAN",
                        help_text="此 URL 是透過哪種方式被發現（初始掃描、爬蟲、JS 抽取、爆破、外部 API）。",
                        max_length=20,
                    ),
                ),
                (
                    "content_fetch_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("SUCCESS_FETCHED", "SUCCESS_FETCHED"),
                            (
                                "SUCCESS_REDIRECTED_EXTERNAL",
                                "SUCCESS_REDIRECTED_EXTERNAL",
                            ),
                            ("FAILED_NO_CONTENT", "FAILED_NO_CONTENT"),
                            ("FAILED_NETWORK_ERROR", "FAILED_NETWORK_ERROR"),
                            ("FAILED_BLOCKED", "FAILED_BLOCKED"),
                            ("FAILED_DNS_ERROR", "FAILED_DNS_ERROR"),
                            ("FAILED_TIMEOUT", "FAILED_TIMEOUT"),
                            ("FAILED_CLIENT_ERROR", "FAILED_CLIENT_ERROR"),
                            ("FAILED_SERVER_ERROR", "FAILED_SERVER_ERROR"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="抓取/下載內容的狀態（成功、失敗原因、是否被導向外部…）。",
                        max_length=30,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        db_index=True,
                        help_text="完整 URL（含 scheme/host/path/query）。在同一個 target 下與 url 組合唯一。",
                        max_length=2048,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        default="GET",
                        help_text="抓取該 URL 時使用的方法（通常為 GET）。",
                        max_length=10,
                    ),
                ),
                (
                    "status_code",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="HTTP status code（若尚未抓取或失敗可為空）。",
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="HTML <title>（若不是 HTML 或未解析則為空）。",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "content_length",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="回應內容長度（bytes），供去重/排序/判斷是否抓到內容。",
                        null=True,
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True,
                        help_text="HTTP response headers（dict/JSON）。",
                        null=True,
                    ),
                ),
                (
                    "raw_response",
                    models.TextField(
                        blank=True,
                        help_text="原始回應內容（可能包含 binary/非 UTF-8 時可視情況留空或存 base64/截斷）。",
                        null=True,
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        help_text="回應內容的文字版本（例如 decoded text）。",
                        null=True,
                    ),
                ),
                (
                    "cleaned_html",
                    models.TextField(
                        blank=True,
                        help_text="清理後的 HTML（去除噪音後，供抽取 link/form/meta 等分析）。",
                        null=True,
                    ),
                ),
                (
                    "raw_response_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="raw_response 的 hash（用於快速去重/比對）。",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "used_flaresolverr",
                    models.BooleanField(
                        default=False,
                        help_text="抓取此 URL 時是否使用 FlareSolverr（通常用於繞過 JS challenge/CF）。",
                    ),
                ),
                (
                    "is_important",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="人工或規則標記的重要 URL（可用於優先分析/報表）。",
                    ),
                ),
                (
                    "is_external_redirect",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="此 URL 最終是否導向到 target 之外（external redirect）。",
                    ),
                ),
                (
                    "final_url",
                    models.URLField(
                        blank=True,
                        help_text="跟隨 redirect 後的最終 URL（如有）。",
                        max_length=2048,
                        null=True,
                    ),
                ),
                (
                    "last_scan_type",
                    models.CharField(
                        blank=True,
                        help_text="最後一次產生/更新此記錄的掃描類型（純紀錄用，可選）。",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "last_scan_id",
                    models.IntegerField(
                        blank=True,
                        help_text="最後一次產生/更新此記錄的掃描 ID（純紀錄用，可選）。",
                        null=True,
                    ),
                ),
                (
                    "is_tech_analyzed",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="此 URL 是否已經進行過技術棧分析。",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="此 URL 所屬的目標（Target）。如果只先綁 subdomain，會在 signal 中自動同步 target。",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.target",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical url result",
                "verbose_name_plural": "historical url results",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalIP",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "ipv4",
                    models.GenericIPAddressField(
                        blank=True, db_index=True, null=True, protocol="ipv4"
                    ),
                ),
                (
                    "ipv6",
                    models.GenericIPAddressField(
                        blank=True, null=True, protocol="ipv6"
                    ),
                ),
                (
                    "last_scan_type",
                    models.CharField(
                        blank=True,
                        help_text="掃描類型 (e.g. NmapScan)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "last_scan_id",
                    models.IntegerField(blank=True, help_text="掃描 ID", null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.target",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical ip",
                "verbose_name_plural": "historical ips",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="AmassScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待處理"),
                            ("RUNNING", "運行中"),
                            ("COMPLETED", "已完成"),
                            ("FAILED", "失敗"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("added_count", models.IntegerField(default=0, help_text="新發現數量")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "which_seed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amass_scans",
                        to="core.seed",
                    ),
                ),
                (
                    "which_target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amass_scans",
                        to="core.target",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="URLResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discovery_source",
                    models.CharField(
                        choices=[
                            ("SCAN", "Initial Scan"),
                            ("CRAWL_html", "Web Crawler (HTML)"),
                            ("JS_EXT", "JS/Xurls Extraction"),
                            ("BRUTE", "Directory Brute Force"),
                            ("API", "External API Discovery"),
                        ],
                        default="SCAN",
                        help_text="此 URL 是透過哪種方式被發現（初始掃描、爬蟲、JS 抽取、爆破、外部 API）。",
                        max_length=20,
                    ),
                ),
                (
                    "content_fetch_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("SUCCESS_FETCHED", "SUCCESS_FETCHED"),
                            (
                                "SUCCESS_REDIRECTED_EXTERNAL",
                                "SUCCESS_REDIRECTED_EXTERNAL",
                            ),
                            ("FAILED_NO_CONTENT", "FAILED_NO_CONTENT"),
                            ("FAILED_NETWORK_ERROR", "FAILED_NETWORK_ERROR"),
                            ("FAILED_BLOCKED", "FAILED_BLOCKED"),
                            ("FAILED_DNS_ERROR", "FAILED_DNS_ERROR"),
                            ("FAILED_TIMEOUT", "FAILED_TIMEOUT"),
                            ("FAILED_CLIENT_ERROR", "FAILED_CLIENT_ERROR"),
                            ("FAILED_SERVER_ERROR", "FAILED_SERVER_ERROR"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="抓取/下載內容的狀態（成功、失敗原因、是否被導向外部…）。",
                        max_length=30,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        db_index=True,
                        help_text="完整 URL（含 scheme/host/path/query）。在同一個 target 下與 url 組合唯一。",
                        max_length=2048,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        default="GET",
                        help_text="抓取該 URL 時使用的方法（通常為 GET）。",
                        max_length=10,
                    ),
                ),
                (
                    "status_code",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="HTTP status code（若尚未抓取或失敗可為空）。",
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="HTML <title>（若不是 HTML 或未解析則為空）。",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "content_length",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="回應內容長度（bytes），供去重/排序/判斷是否抓到內容。",
                        null=True,
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True,
                        help_text="HTTP response headers（dict/JSON）。",
                        null=True,
                    ),
                ),
                (
                    "raw_response",
                    models.TextField(
                        blank=True,
                        help_text="原始回應內容（可能包含 binary/非 UTF-8 時可視情況留空或存 base64/截斷）。",
                        null=True,
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        help_text="回應內容的文字版本（例如 decoded text）。",
                        null=True,
                    ),
                ),
                (
                    "cleaned_html",
                    models.TextField(
                        blank=True,
                        help_text="清理後的 HTML（去除噪音後，供抽取 link/form/meta 等分析）。",
                        null=True,
                    ),
                ),
                (
                    "raw_response_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="raw_response 的 hash（用於快速去重/比對）。",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "used_flaresolverr",
                    models.BooleanField(
                        default=False,
                        help_text="抓取此 URL 時是否使用 FlareSolverr（通常用於繞過 JS challenge/CF）。",
                    ),
                ),
                (
                    "is_important",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="人工或規則標記的重要 URL（可用於優先分析/報表）。",
                    ),
                ),
                (
                    "is_external_redirect",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="此 URL 最終是否導向到 target 之外（external redirect）。",
                    ),
                ),
                (
                    "final_url",
                    models.URLField(
                        blank=True,
                        help_text="跟隨 redirect 後的最終 URL（如有）。",
                        max_length=2048,
                        null=True,
                    ),
                ),
                (
                    "last_scan_type",
                    models.CharField(
                        blank=True,
                        help_text="最後一次產生/更新此記錄的掃描類型（純紀錄用，可選）。",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "last_scan_id",
                    models.IntegerField(
                        blank=True,
                        help_text="最後一次產生/更新此記錄的掃描 ID（純紀錄用，可選）。",
                        null=True,
                    ),
                ),
                (
                    "is_tech_analyzed",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="此 URL 是否已經進行過技術棧分析。",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_subdomains",
                    models.ManyToManyField(
                        blank=True,
                        help_text="此 URL 來源/歸屬的 subdomain（可多個）。用於關聯與後續統計。",
                        related_name="related_urls",
                        to="core.subdomain",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        help_text="此 URL 所屬的目標（Target）。如果只先綁 subdomain，會在 signal 中自動同步 target。",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urls",
                        to="core.target",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="URLAIAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="如果任務失敗，記錄錯誤信息", null=True
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="AI 生成的頁面內容摘要", null=True
                    ),
                ),
                (
                    "inferred_purpose",
                    models.CharField(
                        blank=True,
                        help_text="推斷的頁面功能 (e.g., Login Panel, API Documentation, Blog Post)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "risk_score",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="綜合風險評分 (0-100)", null=True
                    ),
                ),
                (
                    "potential_vulnerabilities",
                    models.JSONField(
                        blank=True,
                        help_text="基於內容和技術棧推斷的潛在漏洞列表",
                        null=True,
                    ),
                ),
                (
                    "recommended_actions",
                    models.JSONField(
                        blank=True, help_text="建議採取的後續行動列表", null=True
                    ),
                ),
                (
                    "command_actions",
                    models.JSONField(
                        blank=True, help_text="建議採取的後續命令列表", null=True
                    ),
                ),
                (
                    "extracted_entities",
                    models.JSONField(
                        blank=True,
                        help_text="提取出的敏感實體 (emails, API keys, etc.)",
                        null=True,
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True,
                        help_text="AI Provider 返回的完整原始 JSON 數據",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "url_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_analyses",
                        to="core.urlresult",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NucleiScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("template_ids", models.JSONField(blank=True, default=list)),
                ("severity_filter", models.CharField(blank=True, max_length=10)),
                ("output_file", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ip_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nuclei_scans",
                        to="core.ip",
                    ),
                ),
                (
                    "subdomain_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nuclei_scans",
                        to="core.subdomain",
                    ),
                ),
                (
                    "url_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nuclei_scans",
                        to="core.urlresult",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MetaTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attributes",
                    models.JSONField(
                        help_text="meta tag 的 attributes（例如 name/property/content）。"
                    ),
                ),
                (
                    "which_url",
                    models.ForeignKey(
                        help_text="此 meta tag 所在的 URLResult。",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta_tags",
                        to="core.urlresult",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("href", models.TextField(help_text="連結位址（原始 href）。")),
                (
                    "text",
                    models.TextField(
                        blank=True, help_text="連結文字（anchor text）。", null=True
                    ),
                ),
                (
                    "which_url",
                    models.ForeignKey(
                        help_text="此 link 所在的 URLResult。",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="core.urlresult",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="javascriptfile",
            name="related_pages",
            field=models.ManyToManyField(
                blank=True,
                help_text="哪些頁面引用/載入了此 JS（script src 或相關關聯）。",
                related_name="javascript_files",
                to="core.urlresult",
            ),
        ),
        migrations.AddField(
            model_name="extractedjs",
            name="which_url",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extracted_js_blocks",
                to="core.urlresult",
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="註解內容（不含 <!-- -->）。")),
                (
                    "which_url",
                    models.ForeignKey(
                        help_text="此 comment 所在的 URLResult。",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="core.urlresult",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="URLScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tool",
                    models.CharField(db_index=True, default="unknown", max_length=50),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "System Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("urls_found_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target_subdomain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans_targeted",
                        to="core.subdomain",
                    ),
                ),
                (
                    "target_url",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans_targeted",
                        to="core.urlresult",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="urlresult",
            name="discovered_by_scans",
            field=models.ManyToManyField(
                help_text="哪些 URLScan 產生或關聯了此 URLResult（可多次、多來源）。",
                related_name="results",
                to="core.urlscan",
            ),
        ),
        migrations.CreateModel(
            name="Endpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        db_index=True,
                        help_text="endpoint path（通常是 /api/v1/...；可含 query template 視你的抽取器而定）。",
                        max_length=2048,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("DELETE", "DELETE"),
                            ("PATCH", "PATCH"),
                            ("OPTIONS", "OPTIONS"),
                            ("HEAD", "HEAD"),
                        ],
                        db_index=True,
                        default="GET",
                        help_text="HTTP method。此欄位搭配 path 與 target 做唯一性判定。",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "discovered_by_inline_js",
                    models.ManyToManyField(
                        blank=True,
                        help_text="哪些內嵌 JS 區塊包含指向此 Endpoint 的 API 呼叫",
                        related_name="found_endpoints",
                        to="core.extractedjs",
                    ),
                ),
                (
                    "discovered_by_js",
                    models.ManyToManyField(
                        blank=True,
                        help_text="哪些 JS 檔案包含指向此 Endpoint 的 API 呼叫",
                        related_name="found_endpoints",
                        to="core.javascriptfile",
                    ),
                ),
                (
                    "related_subdomains",
                    models.ManyToManyField(
                        blank=True,
                        help_text="此 endpoint 相關的 subdomain（可多個）。",
                        related_name="endpoints",
                        to="core.subdomain",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        help_text="此 endpoint 所屬 target。若只先綁 subdomain，會在 signal 中自動同步 target。",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endpoints",
                        to="core.target",
                    ),
                ),
                (
                    "discovered_by_urls",
                    models.ManyToManyField(
                        blank=True,
                        help_text="哪些頁面包含指向此 Endpoint 的連結或表單",
                        related_name="found_endpoints",
                        to="core.urlresult",
                    ),
                ),
                (
                    "discovered_by_scans",
                    models.ManyToManyField(
                        blank=True,
                        help_text="哪些 URLScan 建立/更新了此 endpoint（輔助追溯）。",
                        related_name="endpoints",
                        to="core.urlscan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vulnerability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tool_source", models.CharField(default="nuclei", max_length=50)),
                ("template_id", models.CharField(db_index=True, max_length=255)),
                ("name", models.CharField(max_length=500)),
                ("severity", models.CharField(db_index=True, max_length=20)),
                ("matched_at", models.TextField()),
                ("extracted_results", models.JSONField(blank=True, null=True)),
                ("request_raw", models.TextField(blank=True, null=True)),
                ("response_raw", models.TextField(blank=True, null=True)),
                (
                    "fingerprint",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("status", models.CharField(default="unverified", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.TextField(blank=True, help_text="漏洞詳細描述", null=True),
                ),
                (
                    "last_seen",
                    models.DateTimeField(auto_now=True, help_text="最後一次發現的時間"),
                ),
                (
                    "ip_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vulnerabilities",
                        to="core.ip",
                    ),
                ),
                (
                    "subdomain_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vulnerabilities",
                        to="core.subdomain",
                    ),
                ),
                (
                    "url_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vulnerabilities",
                        to="core.urlresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vulnerability",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Port",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("port_number", models.IntegerField(db_index=True)),
                ("protocol", models.CharField(max_length=10)),
                ("state", models.CharField(db_index=True, max_length=20)),
                (
                    "service_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "service_version",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "last_scan_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("last_scan_id", models.IntegerField(blank=True, null=True)),
                (
                    "discovered_by_scans",
                    models.ManyToManyField(
                        blank=True, related_name="ports_updated", to="core.nmapscan"
                    ),
                ),
                (
                    "ip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ports",
                        to="core.ip",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ip", "port_number"], name="core_port_ip_id_8d102b_idx"
                    )
                ],
                "unique_together": {("ip", "port_number", "protocol")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="seed",
            unique_together={("target", "value")},
        ),
        migrations.CreateModel(
            name="URLParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True, help_text="參數名稱（key）。", max_length=255
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        blank=True,
                        help_text="觀察到的範例值（可用於推斷型別/敏感度），不保證每次都有。",
                        null=True,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("form", "Form"),
                            ("javascript", "JS"),
                            ("querystring", "QueryString"),
                        ],
                        help_text="參數來源（表單/JS 抽取/querystring）。",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "param_location",
                    models.CharField(
                        choices=[("query", "Query String"), ("body", "Body")],
                        default="query",
                        help_text="參數位置（query 或 body）。",
                        max_length=10,
                    ),
                ),
                (
                    "param_hash",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="由 which_endpoint + param_location + key 計算出的 sha256，用於加速查詢/比對。",
                        max_length=64,
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        blank=True,
                        help_text="推斷出的型別（如 string/int/bool/json 等；可選）。",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "line_number",
                    models.IntegerField(
                        blank=True,
                        help_text="若從原始檔案/內容抽取，記錄行號方便回溯（可選）。",
                        null=True,
                    ),
                ),
                (
                    "which_endpoint",
                    models.ForeignKey(
                        help_text="此參數所屬 endpoint。",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="query_parameters",
                        to="core.endpoint",
                    ),
                ),
            ],
            options={
                "unique_together": {("which_endpoint", "param_location", "key")},
            },
        ),
        migrations.CreateModel(
            name="TechStack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="技術名稱，如 PHP, Nginx",
                        max_length=100,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True, help_text="版本號", max_length=100, null=True
                    ),
                ),
                (
                    "categories",
                    models.JSONField(
                        default=list,
                        help_text="分類，如 ['Web servers', 'Reverse proxies']",
                    ),
                ),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "subdomain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technologies",
                        to="core.subdomain",
                    ),
                ),
                (
                    "which_url_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technologies",
                        to="core.urlresult",
                    ),
                ),
            ],
            options={
                "unique_together": {("which_url_result", "name", "version")},
            },
        ),
        migrations.CreateModel(
            name="Iframe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("src", models.TextField(help_text="iframe src（原始值）。")),
                (
                    "which_url",
                    models.ForeignKey(
                        help_text="此 iframe 所在的 URLResult。",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="iframes",
                        to="core.urlresult",
                    ),
                ),
            ],
            options={
                "unique_together": {("which_url", "src")},
            },
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="form action（可能是相對路徑或完整 URL）。",
                        max_length=2048,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        help_text="form method（GET/POST…）。", max_length=10
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict,
                        help_text="解析到的 input/select/textarea 等欄位（原始結構）。",
                    ),
                ),
                (
                    "which_url",
                    models.ForeignKey(
                        help_text="此表單所在的 URLResult（頁面）。",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forms",
                        to="core.urlresult",
                    ),
                ),
            ],
            options={
                "unique_together": {("which_url", "action", "method")},
            },
        ),
        migrations.CreateModel(
            name="AnalysisFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pattern_name",
                    models.CharField(
                        db_index=True, help_text="命中的規則/模式名稱。", max_length=100
                    ),
                ),
                (
                    "line_number",
                    models.PositiveIntegerField(
                        help_text="命中行號（若有行號概念，例如對 text/cleaned_html 做 line split）。"
                    ),
                ),
                ("match_content", models.TextField(help_text="命中的文字片段。")),
                (
                    "match_start",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="命中起始位置（字元 index，可選）。",
                        null=True,
                    ),
                ),
                (
                    "match_end",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="命中結束位置（字元 index，可選）。",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "which_url_result",
                    models.ForeignKey(
                        help_text="命中的 URLResult。",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="core.urlresult",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("which_url_result", "pattern_name", "line_number")
                },
            },
        ),
        migrations.AddIndex(
            model_name="urlscan",
            index=models.Index(
                fields=["status", "created_at"], name="core_urlsca_status_c56373_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="urlresult",
            unique_together={("target", "url")},
        ),
        migrations.AddIndex(
            model_name="endpoint",
            index=models.Index(
                fields=["path", "method"], name="core_endpoi_path_f97a43_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="endpoint",
            unique_together={("target", "method", "path")},
        ),
    ]
