# Generated by Django 5.2.4 on 2025-12-25 04:37

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ipv4",
                    models.GenericIPAddressField(
                        blank=True, db_index=True, null=True, protocol="ipv4"
                    ),
                ),
                (
                    "ipv6",
                    models.GenericIPAddressField(
                        blank=True, null=True, protocol="ipv6"
                    ),
                ),
                (
                    "last_scan_type",
                    models.CharField(
                        blank=True,
                        help_text="掃描類型 (e.g. NmapScan)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "last_scan_id",
                    models.IntegerField(blank=True, help_text="掃描 ID", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Seed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="種子內容，如 google.com", max_length=512
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DOMAIN", "Root Domain (e.g., google.com)"),
                            ("IP_RANGE", "IP/CIDR (e.g., 192.168.1.0/24)"),
                            ("URL", "Specific URL (e.g., https://api.site.com)"),
                        ],
                        default="DOMAIN",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="是否啟用此種子進行掃描"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subdomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sources_text",
                    models.TextField(
                        blank=True, help_text="Comma-separated list of sources"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("dns_records", models.JSONField(blank=True, null=True)),
                ("cname", models.TextField(blank=True, null=True)),
                ("is_resolvable", models.BooleanField(default=True)),
                ("is_cdn", models.BooleanField(default=False)),
                ("is_waf", models.BooleanField(default=False)),
                ("waf_name", models.TextField(null=True)),
                ("cdn_name", models.TextField(null=True)),
                (
                    "last_scan_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("last_scan_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="專案名稱，如 'Google'", max_length=255, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="專案描述與備註", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="URLResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_fetch_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("SUCCESS_FETCHED", "SUCCESS_FETCHED"),
                            ("FAILED_NO_CONTENT", "FAILED_NO_CONTENT"),
                            ("FAILED_NETWORK_ERROR", "FAILED_NETWORK_ERROR"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(db_index=True, max_length=2048, unique=True)),
                (
                    "status_code",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("title", models.CharField(blank=True, max_length=512, null=True)),
                ("content_length", models.PositiveIntegerField(blank=True, null=True)),
                ("headers", models.JSONField(blank=True, null=True)),
                ("tech_stack", models.JSONField(blank=True, null=True)),
                ("raw_response", models.TextField(blank=True, null=True)),
                ("is_important", models.BooleanField(db_index=True, default=False)),
                ("used_flaresolverr", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "final_url",
                    models.URLField(
                        blank=True, db_index=True, max_length=2048, null=True
                    ),
                ),
                (
                    "is_external_redirect",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "last_scan_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("last_scan_id", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalIP",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "ipv4",
                    models.GenericIPAddressField(
                        blank=True, db_index=True, null=True, protocol="ipv4"
                    ),
                ),
                (
                    "ipv6",
                    models.GenericIPAddressField(
                        blank=True, null=True, protocol="ipv6"
                    ),
                ),
                (
                    "last_scan_type",
                    models.CharField(
                        blank=True,
                        help_text="掃描類型 (e.g. NmapScan)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "last_scan_id",
                    models.IntegerField(blank=True, help_text="掃描 ID", null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical ip",
                "verbose_name_plural": "historical ips",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSubdomain",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "sources_text",
                    models.TextField(
                        blank=True, help_text="Comma-separated list of sources"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("first_seen", models.DateTimeField(blank=True, editable=False)),
                ("last_seen", models.DateTimeField(blank=True, editable=False)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("dns_records", models.JSONField(blank=True, null=True)),
                ("cname", models.TextField(blank=True, null=True)),
                ("is_resolvable", models.BooleanField(default=True)),
                ("is_cdn", models.BooleanField(default=False)),
                ("is_waf", models.BooleanField(default=False)),
                ("waf_name", models.TextField(null=True)),
                ("cdn_name", models.TextField(null=True)),
                (
                    "last_scan_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("last_scan_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "which_seed",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.seed",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical subdomain",
                "verbose_name_plural": "historical subdomains",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalURLResult",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "content_fetch_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("SUCCESS_FETCHED", "SUCCESS_FETCHED"),
                            ("FAILED_NO_CONTENT", "FAILED_NO_CONTENT"),
                            ("FAILED_NETWORK_ERROR", "FAILED_NETWORK_ERROR"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(db_index=True, max_length=2048)),
                (
                    "status_code",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("title", models.CharField(blank=True, max_length=512, null=True)),
                ("content_length", models.PositiveIntegerField(blank=True, null=True)),
                ("headers", models.JSONField(blank=True, null=True)),
                ("tech_stack", models.JSONField(blank=True, null=True)),
                ("raw_response", models.TextField(blank=True, null=True)),
                ("is_important", models.BooleanField(db_index=True, default=False)),
                ("used_flaresolverr", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "final_url",
                    models.URLField(
                        blank=True, db_index=True, max_length=2048, null=True
                    ),
                ),
                (
                    "is_external_redirect",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "last_scan_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("last_scan_id", models.IntegerField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical url result",
                "verbose_name_plural": "historical url results",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="IPAIAnalysis",
            fields=[
                (
                    "ip",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="ai_analysis",
                        serialize=False,
                        to="core.ip",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="如果任務失敗，記錄錯誤信息", null=True
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="AI 生成的關於此 IP 的一句話總結",
                        null=True,
                    ),
                ),
                (
                    "inferred_purpose",
                    models.TextField(
                        blank=True,
                        help_text="推斷的服務器用途 (e.g., Web Server, Mail Server, C2)",
                        null=True,
                    ),
                ),
                (
                    "risk_score",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="綜合風險評分 (0-100)", null=True
                    ),
                ),
                (
                    "potential_vulnerabilities",
                    models.JSONField(
                        blank=True,
                        help_text="基於開放端口和服務推斷的潛在漏洞列表",
                        null=True,
                    ),
                ),
                (
                    "recommended_actions",
                    models.JSONField(
                        blank=True, help_text="建議採取的後續行動列表", null=True
                    ),
                ),
                (
                    "command_actions",
                    models.JSONField(
                        blank=True, help_text="建議採取的後續命令列表", null=True
                    ),
                ),
                (
                    "port_analysis_summary",
                    models.TextField(
                        blank=True, help_text="對開放端口和服務的綜合分析", null=True
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True,
                        help_text="AI Provider 返回的完整原始 JSON 數據",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalPort",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("port_number", models.IntegerField(db_index=True)),
                ("protocol", models.CharField(max_length=10)),
                ("state", models.CharField(db_index=True, max_length=20)),
                (
                    "service_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "service_version",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("first_seen", models.DateTimeField(blank=True, editable=False)),
                ("last_seen", models.DateTimeField(blank=True, editable=False)),
                (
                    "last_scan_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("last_scan_id", models.IntegerField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ip",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.ip",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical port",
                "verbose_name_plural": "historical ports",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="NmapScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待處理"),
                            ("RUNNING", "運行中"),
                            ("COMPLETED", "已完成"),
                            ("FAILED", "失敗"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("nmap_args", models.TextField()),
                ("nmap_output", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "target_ip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.ip",
                    ),
                ),
                (
                    "which_seed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nmap_scans",
                        to="core.seed",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ip",
            name="which_seed",
            field=models.ManyToManyField(related_name="ips", to="core.seed"),
        ),
        migrations.CreateModel(
            name="SubdomainAIAnalysis",
            fields=[
                (
                    "subdomain",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="ai_analysis",
                        serialize=False,
                        to="core.subdomain",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="如果任務失敗，記錄錯誤信息", null=True
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="AI 生成的關於此子域名用途和重要性的總結",
                        null=True,
                    ),
                ),
                (
                    "inferred_purpose",
                    models.TextField(
                        blank=True,
                        help_text="推斷的子域名用途 (e.g., Main Website, API Endpoint, Staging Environment, Blog)",
                        null=True,
                    ),
                ),
                (
                    "risk_score",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="綜合風險評分 (0-100)", null=True
                    ),
                ),
                (
                    "potential_vulnerabilities",
                    models.JSONField(
                        blank=True,
                        help_text="基於其屬性推斷的潛在攻擊向量/漏洞列表",
                        null=True,
                    ),
                ),
                (
                    "recommended_actions",
                    models.JSONField(
                        blank=True, help_text="建議採取的後續行動列表", null=True
                    ),
                ),
                (
                    "command_actions",
                    models.JSONField(
                        blank=True, help_text="建議採取的後續命令列表", null=True
                    ),
                ),
                (
                    "business_impact",
                    models.CharField(
                        blank=True,
                        help_text="推斷的業務重要性 (e.g., Critical, High, Medium, Low)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "tech_stack_summary",
                    models.TextField(
                        blank=True,
                        help_text="對其技術棧的風險分析 (e.g., 'Runs outdated WordPress')",
                        null=True,
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True,
                        help_text="AI Provider 返回的完整原始 JSON 數據",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="subdomain",
            name="ips",
            field=models.ManyToManyField(
                blank=True, related_name="subdomains", to="core.ip"
            ),
        ),
        migrations.AddField(
            model_name="subdomain",
            name="which_seed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subdomains",
                to="core.seed",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalSubdomain_ips",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.historicalsubdomain",
                    ),
                ),
                (
                    "ip",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.ip",
                    ),
                ),
                (
                    "subdomain",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.subdomain",
                    ),
                ),
            ],
            options={
                "verbose_name": "HistoricalSubdomain_ips",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="SubfinderScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待處理"),
                            ("RUNNING", "運行中"),
                            ("COMPLETED", "已完成"),
                            ("FAILED", "失敗"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("added_count", models.IntegerField(default=0, help_text="新發現數量")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "which_seed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfinder_scans",
                        to="core.seed",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="subdomain",
            name="discovered_by_scans",
            field=models.ManyToManyField(
                blank=True, related_name="updated_subdomains", to="core.subfinderscan"
            ),
        ),
        migrations.AddField(
            model_name="seed",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seeds",
                to="core.target",
            ),
        ),
        migrations.CreateModel(
            name="URLAIAnalysis",
            fields=[
                (
                    "url_result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="ai_analysis",
                        serialize=False,
                        to="core.urlresult",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="如果任務失敗，記錄錯誤信息", null=True
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="AI 生成的頁面內容摘要", null=True
                    ),
                ),
                (
                    "inferred_purpose",
                    models.CharField(
                        blank=True,
                        help_text="推斷的頁面功能 (e.g., Login Panel, API Documentation, Blog Post)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "risk_score",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="綜合風險評分 (0-100)", null=True
                    ),
                ),
                (
                    "potential_vulnerabilities",
                    models.JSONField(
                        blank=True,
                        help_text="基於內容和技術棧推斷的潛在漏洞列表",
                        null=True,
                    ),
                ),
                (
                    "recommended_actions",
                    models.JSONField(
                        blank=True, help_text="建議採取的後續行動列表", null=True
                    ),
                ),
                (
                    "command_actions",
                    models.JSONField(
                        blank=True, help_text="建議採取的後續命令列表", null=True
                    ),
                ),
                (
                    "extracted_entities",
                    models.JSONField(
                        blank=True,
                        help_text="提取出的敏感實體 (emails, API keys, etc.)",
                        null=True,
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True,
                        help_text="AI Provider 返回的完整原始 JSON 數據",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MetaTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attributes", models.JSONField()),
                (
                    "which_url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta_tags",
                        to="core.urlresult",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("href", models.TextField()),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "which_url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="core.urlresult",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JavaScriptFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("src", models.TextField(blank=True, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "which_url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="js_files",
                        to="core.urlresult",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Iframe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("src", models.TextField()),
                (
                    "which_url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="iframes",
                        to="core.urlresult",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=2048)),
                ("method", models.CharField(max_length=10)),
                ("parameters", models.JSONField(default=dict)),
                (
                    "which_url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forms",
                        to="core.urlresult",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Endpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=2048)),
                ("source", models.CharField(max_length=50)),
                (
                    "which_url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endpoints",
                        to="core.urlresult",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "which_url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="core.urlresult",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnalysisFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pattern_name", models.CharField(db_index=True, max_length=100)),
                ("line_number", models.PositiveIntegerField()),
                ("match_content", models.TextField()),
                ("match_start", models.PositiveIntegerField(blank=True, null=True)),
                ("match_end", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "which_url_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="core.urlresult",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="URLScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "which_subdomain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="url_scans",
                        to="core.subdomain",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="urlresult",
            name="discovered_by_scans",
            field=models.ManyToManyField(related_name="results", to="core.urlscan"),
        ),
        migrations.CreateModel(
            name="Port",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("port_number", models.IntegerField(db_index=True)),
                ("protocol", models.CharField(max_length=10)),
                ("state", models.CharField(db_index=True, max_length=20)),
                (
                    "service_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "service_version",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "last_scan_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("last_scan_id", models.IntegerField(blank=True, null=True)),
                (
                    "discovered_by_scans",
                    models.ManyToManyField(
                        blank=True, related_name="ports_updated", to="core.nmapscan"
                    ),
                ),
                (
                    "ip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ports",
                        to="core.ip",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ip", "port_number"], name="core_port_ip_id_8d102b_idx"
                    )
                ],
                "unique_together": {("ip", "port_number", "protocol")},
            },
        ),
        migrations.AddIndex(
            model_name="subdomain",
            index=models.Index(
                fields=["which_seed", "name"], name="core_subdom_which_s_e6fc4a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subdomain",
            unique_together={("which_seed", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="seed",
            unique_together={("target", "value")},
        ),
        migrations.AddConstraint(
            model_name="javascriptfile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("src__isnull", False), ("content__isnull", False), _connector="OR"
                ),
                name="js_src_or_content_not_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="javascriptfile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("src__isnull", False)),
                fields=("which_url", "src"),
                name="unique_js_src_per_url",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="iframe",
            unique_together={("which_url", "src")},
        ),
        migrations.AlterUniqueTogether(
            name="form",
            unique_together={("which_url", "action", "method")},
        ),
        migrations.AlterUniqueTogether(
            name="endpoint",
            unique_together={("which_url", "path")},
        ),
        migrations.AlterUniqueTogether(
            name="analysisfinding",
            unique_together={("which_url_result", "pattern_name", "line_number")},
        ),
        migrations.AddIndex(
            model_name="urlscan",
            index=models.Index(
                fields=["status", "created_at"], name="core_urlsca_status_c56373_idx"
            ),
        ),
    ]
