# Generated by Django 5.2.8 on 2026-05-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdomainaianalysis',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='subdomainaianalysis',
            name='subdomain',
        ),
        migrations.RemoveField(
            model_name='subdomainaianalysis',
            name='triggered_by_step',
        ),
        migrations.RemoveField(
            model_name='urlaianalysis',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='urlaianalysis',
            name='triggered_by_step',
        ),
        migrations.RemoveField(
            model_name='urlaianalysis',
            name='url_result',
        ),
        migrations.AlterField(
            model_name='initialaianalysis',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='initialaianalysis',
            name='inferred_purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='initialaianalysis',
            name='is_converted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='initialaianalysis',
            name='raw_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='initialaianalysis',
            name='risk_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='initialaianalysis',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='initialaianalysis',
            name='worth_deep_analysis',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='IPAIAnalysis',
        ),
        migrations.DeleteModel(
            name='SubdomainAIAnalysis',
        ),
        migrations.DeleteModel(
            name='URLAIAnalysis',
        ),
    ]
