# Generated by Django 5.2.4 on 2026-03-13 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ipaianalysis",
            name="inferred_purpose",
        ),
        migrations.RemoveField(
            model_name="ipaianalysis",
            name="risk_score",
        ),
        migrations.RemoveField(
            model_name="ipaianalysis",
            name="summary",
        ),
        migrations.RemoveField(
            model_name="subdomainaianalysis",
            name="inferred_purpose",
        ),
        migrations.RemoveField(
            model_name="subdomainaianalysis",
            name="risk_score",
        ),
        migrations.RemoveField(
            model_name="subdomainaianalysis",
            name="summary",
        ),
        migrations.RemoveField(
            model_name="urlaianalysis",
            name="inferred_purpose",
        ),
        migrations.RemoveField(
            model_name="urlaianalysis",
            name="risk_score",
        ),
        migrations.RemoveField(
            model_name="urlaianalysis",
            name="summary",
        ),
        migrations.CreateModel(
            name="InitialAIAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="如果任務失敗，記錄錯誤信息", null=True
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="AI 生成的關於此資產的一句話總結",
                        null=True,
                    ),
                ),
                (
                    "inferred_purpose",
                    models.TextField(
                        blank=True,
                        help_text="推斷的用途 (e.g., Web Server, API Endpoint)",
                        null=True,
                    ),
                ),
                (
                    "worth_deep_analysis",
                    models.BooleanField(
                        default=False,
                        help_text="AI 判斷是否值得進一步深度分析建立攻擊計畫",
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True,
                        help_text="AI Provider 返回的完整原始 JSON 數據",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initial_ai_analyses",
                        to="core.ip",
                    ),
                ),
                (
                    "subdomain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initial_ai_analyses",
                        to="core.subdomain",
                    ),
                ),
                (
                    "url_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initial_ai_analyses",
                        to="core.urlresult",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StepNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "risk_score",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="綜合風險分數 (0-100)", null=True
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="AI 的筆記內容或分析細節", null=True
                    ),
                ),
                (
                    "ai_thoughts",
                    models.TextField(
                        blank=True, help_text="AI 對於這個 Step 的推理過程", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "step",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_detail",
                        to="core.step",
                    ),
                ),
            ],
        ),
    ]
