# Generated by Django 5.2.4 on 2026-02-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="endpoint",
            name="discovered_by_inline_js",
            field=models.ManyToManyField(
                blank=True,
                help_text="哪些內嵌 JS 區塊包含指向此 Endpoint 的 API 呼叫",
                related_name="found_endpoints",
                to="core.extractedjs",
            ),
        ),
    ]
