# Generated by Django 5.2.4 on 2025-12-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalurlresult",
            name="raw_response_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="urlresult",
            name="raw_response_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
