# Generated by Django 5.2.4 on 2025-12-27 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_historicalurlresult_raw_response_hash_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="urlscan",
            name="which_subdomain",
        ),
        migrations.AddField(
            model_name="urlresult",
            name="related_subdomains",
            field=models.ManyToManyField(
                blank=True, related_name="related_urls", to="core.subdomain"
            ),
        ),
        migrations.AddField(
            model_name="urlscan",
            name="target_subdomain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scans_targeted",
                to="core.subdomain",
            ),
        ),
        migrations.AddField(
            model_name="urlscan",
            name="target_url",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scans_targeted",
                to="core.urlresult",
            ),
        ),
        migrations.AddField(
            model_name="urlscan",
            name="tool",
            field=models.CharField(
                default="unknown",
                help_text="使用的工具 (e.g. gau, katana)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="urlscan",
            name="urls_found_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="historicalurlresult",
            name="raw_response_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="urlresult",
            name="raw_response_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
