# Generated by Django 5.2.4 on 2026-05-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_subdomainaianalysis_overview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='operation_type',
            field=models.CharField(blank=True, help_text='操作類型，例如 AI_AUTOMATION_EXECUTION', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
