# Generated by Django 5.2.4 on 2026-02-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_endpoint_discovered_by_inline_js"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractedjs",
            name="last_seen",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
