# Generated by Django 5.2.4 on 2026-03-14 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_ipaianalysis_inferred_purpose_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payload",
            name="step",
        ),
        migrations.RemoveField(
            model_name="stepnote",
            name="risk_score",
        ),
        migrations.AddField(
            model_name="overview",
            name="business_impact",
            field=models.CharField(
                blank=True,
                help_text="推斷的業務重要性 (e.g., Critical, High, Medium, Low)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="payload",
            name="attack_vector",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payloads",
                to="core.attackvector",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="overview",
            name="summary",
            field=models.TextField(blank=True, help_text="目前目標的筆記", null=True),
        ),
    ]
