# Generated by Django 5.2.4 on 2026-03-14 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_payload_step_remove_stepnote_risk_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='step',
            name='subdomain',
        ),
        migrations.RemoveField(
            model_name='step',
            name='url_result',
        ),
    ]
