# Generated by Django 5.2.8 on 2026-05-19 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_step_operation_type_and_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_content', models.TextField(help_text='執行的腳本代碼')),
                ('script_language', models.CharField(choices=[('python', 'Python'), ('bash', 'Bash')], default='python', help_text='腳本語言', max_length=20)),
                ('args_string', models.TextField(blank=True, help_text='傳遞給腳本的命令行參數', null=True)),
                ('input_json', models.JSONField(blank=True, help_text='結構化的輸入參數（JSON）', null=True)),
                ('status', models.CharField(choices=[('PENDING', '待執行'), ('RUNNING', '執行中'), ('SUCCESS', '成功'), ('FAILED', '失敗'), ('TIMEOUT', '逾時')], default='PENDING', max_length=10)),
                ('exit_code', models.IntegerField(blank=True, help_text='腳本退出碼', null=True)),
                ('raw_output', models.TextField(blank=True, help_text='腳本的原始輸出', null=True)),
                ('output_json', models.JSONField(blank=True, help_text='結構化的輸出（JSON），如果腳本輸出了 JSON）', null=True)),
                ('error_message', models.TextField(blank=True, help_text='執行錯誤訊息', null=True)),
                ('validation_status', models.CharField(choices=[('NOT_VALIDATED', '未驗證'), ('INPUT_INVALID', '輸入驗證失敗'), ('OUTPUT_INVALID', '輸出驗證失敗'), ('VALIDATED', '驗證通過'), ('VALIDATION_ERROR', '驗證過程出錯')], default='NOT_VALIDATED', help_text='輸入/輸出類型驗證狀態', max_length=20)),
                ('validation_error', models.TextField(blank=True, help_text='驗證失敗的原因', null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='執行開始時間')),
                ('completed_at', models.DateTimeField(blank=True, help_text='執行完成時間', null=True)),
                ('execution_duration_ms', models.IntegerField(blank=True, help_text='執行耗時（毫秒）', null=True)),
            ],
            options={
                'verbose_name': '腳本執行記錄',
                'verbose_name_plural': '腳本執行歷史',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='skilltemplate',
            options={'ordering': ['-is_robust', '-usage_count', '-updated_at'], 'verbose_name': 'Skill 技能', 'verbose_name_plural': 'Skill 技能庫'},
        ),
        migrations.AddField(
            model_name='skilltemplate',
            name='input_schema',
            field=models.JSONField(blank=True, default=dict, help_text="執行前需要驗證的輸入參數 JSON Schema。例如：{'type': 'object', 'properties': {'url': {'type': 'string'}}, 'required': ['url']}", null=True),
        ),
        migrations.AddField(
            model_name='skilltemplate',
            name='is_robust',
            field=models.BooleanField(default=False, help_text='標記此技能已多次驗證、輸入輸出穩定，不再允許任意修改。避免 AI 意外破壞經過驗證的技能。'),
        ),
        migrations.AddField(
            model_name='skilltemplate',
            name='last_failure_reason',
            field=models.TextField(blank=True, help_text='最近一次執行失敗的原因與錯誤訊息。用於 AI 診斷問題。', null=True),
        ),
        migrations.AddField(
            model_name='skilltemplate',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, help_text='上次成功執行並通過輸出驗證的時間。如果距離現在超過 7 天，應進行重驗證。', null=True),
        ),
        migrations.AddField(
            model_name='skilltemplate',
            name='output_schema',
            field=models.JSONField(blank=True, default=dict, help_text='腳本輸出的預期 JSON Schema。用於驗證腳本是否按預期格式輸出。', null=True),
        ),
        migrations.AddField(
            model_name='skilltemplate',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='技能版本號。當修改已驗證的技能時自動遞增。'),
        ),
        migrations.AlterField(
            model_name='skilltemplate',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('bash', 'Bash')], default='python', help_text='腳本語言', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='skilltemplate',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='unique_skill_version'),
        ),
        migrations.AddField(
            model_name='scriptexecution',
            name='attack_vector',
            field=models.ForeignKey(blank=True, help_text='關聯的攻擊向量（便於導出該向量的所有腳本）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='script_executions', to='core.attackvector'),
        ),
        migrations.AddField(
            model_name='scriptexecution',
            name='skill',
            field=models.ForeignKey(blank=True, help_text='關聯的 SkillTemplate（如果腳本已保存到庫），否則為空', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='core.skilltemplate'),
        ),
        migrations.AddField(
            model_name='scriptexecution',
            name='step',
            field=models.ForeignKey(help_text='觸發此次執行的 Step', on_delete=django.db.models.deletion.CASCADE, related_name='script_executions', to='core.step'),
        ),
        migrations.AddIndex(
            model_name='scriptexecution',
            index=models.Index(fields=['step', '-started_at'], name='core_script_step_id_b225da_idx'),
        ),
        migrations.AddIndex(
            model_name='scriptexecution',
            index=models.Index(fields=['attack_vector', '-started_at'], name='core_script_attack__50543f_idx'),
        ),
        migrations.AddIndex(
            model_name='scriptexecution',
            index=models.Index(fields=['skill', '-started_at'], name='core_script_skill_i_768dcb_idx'),
        ),
        migrations.AddIndex(
            model_name='scriptexecution',
            index=models.Index(fields=['status'], name='core_script_status_3dbfd1_idx'),
        ),
    ]
