# Generated by Django 5.2.4 on 2026-02-14 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_extractedjs_last_seen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extractedjs",
            name="last_seen",
        ),
        migrations.AlterField(
            model_name="extractedjs",
            name="which_url",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extracted_js_blocks",
                to="core.urlresult",
            ),
        ),
    ]
