# Generated by Django 5.2.4 on 2025-12-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_urlscan_which_subdomain_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nmapscan",
            name="target_ip",
        ),
        migrations.AddField(
            model_name="ip",
            name="discovered_by_scans",
            field=models.ManyToManyField(
                blank=True, related_name="ips_discovered", to="core.nmapscan"
            ),
        ),
    ]
