# Generated by Django 5.2.4 on 2026-02-17 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_extractedjs_last_seen_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubBrute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待處理"),
                            ("RUNNING", "運行中"),
                            ("COMPLETED", "已完成"),
                            ("FAILED", "失敗"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("added_count", models.IntegerField(default=0, help_text="新發現數量")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "which_sub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="SubBrute",
                        to="core.subdomain",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
