# Generated by Django 5.2.8 on 2026-05-21 10:47

import django.db.models.deletion
from django.db import migrations, models


def clean_invalid_thread_ids(apps, schema_editor):
    Overview = apps.get_model('core', 'Overview')
    Thread = apps.get_model('ai_assistant', 'Thread')
    
    # Get all valid thread IDs
    valid_thread_ids = set(Thread.objects.values_list('id', flat=True))
    
    # Update overviews with invalid thread_id to None
    for overview in Overview.objects.all():
        updated = False
        if overview.thread_id is not None and overview.thread_id not in valid_thread_ids:
            overview.thread_id = None
            updated = True
        if overview.parent_thread_id is not None and overview.parent_thread_id not in valid_thread_ids:
            overview.parent_thread_id = None
            updated = True
        if updated:
            overview.save(update_fields=['thread_id', 'parent_thread_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_scriptexecution_alter_skilltemplate_options_and_more'),
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(clean_invalid_thread_ids, reverse_code=migrations.RunPython.noop),
        migrations.RenameField(
            model_name='overview',
            old_name='thread_id',
            new_name='thread',
        ),
        migrations.RenameField(
            model_name='overview',
            old_name='parent_thread_id',
            new_name='parent_thread',
        ),
        migrations.AlterField(
            model_name='overview',
            name='thread',
            field=models.ForeignKey(blank=True, db_column='thread_id', help_text='筆記本 Overview 的 AI 對話 Thread (for push-callback)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overviews', to='ai_assistant.thread'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='parent_thread',
            field=models.ForeignKey(blank=True, db_column='parent_thread_id', help_text='建立此任務的上層節點/Caller Thread (for async completion callback)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_overviews', to='ai_assistant.thread'),
        ),
    ]
