# Generated by Django 5.2.4 on 2026-02-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_subbrute"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalurlresult",
            name="is_tech_analyzed",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="此 URL 是否已經進行過技術棧分析。",
            ),
        ),
        migrations.AddField(
            model_name="urlresult",
            name="is_tech_analyzed",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="此 URL 是否已經進行過技術棧分析。",
            ),
        ),
    ]
