# Generated by Django 5.2.4 on 2025-12-31 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_vulnerability"),
    ]

    operations = [
        migrations.CreateModel(
            name="NucleiScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_ids", models.JSONField(blank=True, default=list)),
                ("severity_filter", models.CharField(blank=True, max_length=10)),
                ("output_file", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ip_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nuclei_scans",
                        to="core.ip",
                    ),
                ),
                (
                    "subdomain_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nuclei_scans",
                        to="core.subdomain",
                    ),
                ),
                (
                    "url_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nuclei_scans",
                        to="core.urlresult",
                    ),
                ),
            ],
        ),
    ]
