# Generated by Django 5.2.8 on 2026-03-14 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_step_ip_step_subdomain_step_url_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialaianalysis',
            name='is_converted',
            field=models.BooleanField(default=False, help_text='是否已轉換為 Overview'),
        ),
        migrations.AddField(
            model_name='initialaianalysis',
            name='overview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initial_analyses', to='core.overview'),
        ),
    ]
