# Generated by Django 5.2.4 on 2026-02-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_historicalurlresult_is_tech_analyzed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsubdomain",
            name="is_tech_analyzed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subdomain",
            name="is_tech_analyzed",
            field=models.BooleanField(default=False),
        ),
    ]
