# Generated by Django 5.2.8 on 2026-05-23 07:24

import django.db.models.deletion
from django.db import migrations, models


def clear_old_skills(apps, schema_editor):
    SkillTemplate = apps.get_model('core', 'SkillTemplate')
    SkillTemplate.objects.all().delete()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('core', '0006_add_skill_io_contract_verification_merge'),
    ]

    operations = [
        migrations.RunPython(clear_old_skills),
        migrations.RenameIndex(
            model_name='skillmergeevaluation',
            new_name='core_skill__skill_a_60375d_idx',
            old_name='core_skill__skill_a_57509f',
        ),
        migrations.RenameIndex(
            model_name='skillmergeevaluation',
            new_name='core_skill__is_merg_d3ad1d_idx',
            old_name='core_skill__is_merg_da4bcc',
        ),
        migrations.RenameIndex(
            model_name='skillverification',
            new_name='core_skill__skill_i_5df24b_idx',
            old_name='core_skill__skill_i_08974d',
        ),
        migrations.RenameIndex(
            model_name='skillverification',
            new_name='core_skill__verdict_baf13d_idx',
            old_name='core_skill__verdict_41e300',
        ),
        migrations.AddField(
            model_name='skilltemplate',
            name='script_body',
            field=models.TextField(blank=True, help_text='腳本核心邏輯（僅含 main() 函式實作）。禁止在此欄位寫 I/O 處理代碼（sys.argv/argparse/print）。I/O Contract 由系統根據 input_schema/output_schema 自動注入。格式規範：def main(inputs: SkillInput) -> None:', null=True),
        ),
        migrations.AlterField(
            model_name='skillmergeevaluation',
            name='evaluated_at',
            field=models.DateTimeField(auto_now_add=True, help_text='本次評估時間'),
        ),
        migrations.AlterField(
            model_name='skillmergeevaluation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='skillmergeevaluation',
            name='merge_strategy',
            field=models.CharField(blank=True, choices=[('NOT_RECOMMENDED', '不建議合併'), ('CONCAT', '串聯 — 合併 instructions 與 tags，保留各自 script'), ('UNION', 'Union — 合併 schema 與全部內容'), ('LATEST_ONLY', '取最新 — 保留版本較新的技能'), ('SMART_MERGE', '智能合併 — 自動融合 script 與 instructions'), ('A_MERGES_INTO_B', 'A 併入 B — A 的功能是 B 的子集'), ('B_MERGES_INTO_A', 'B 併入 A — B 的功能是 A 的子集')], help_text='建議的合併策略', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='skillmergeevaluation',
            name='skill_a',
            field=models.ForeignKey(help_text='技能 A（評估對中的第一個）', on_delete=django.db.models.deletion.CASCADE, related_name='merge_evals_as_a', to='core.skilltemplate'),
        ),
        migrations.AlterField(
            model_name='skillmergeevaluation',
            name='skill_b',
            field=models.ForeignKey(help_text='技能 B（評估對中的第二個）', on_delete=django.db.models.deletion.CASCADE, related_name='merge_evals_as_b', to='core.skilltemplate'),
        ),
        migrations.AlterField(
            model_name='skillverification',
            name='executed_at',
            field=models.DateTimeField(auto_now_add=True, help_text='驗證執行時間'),
        ),
        migrations.AlterField(
            model_name='skillverification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='skillverification',
            name='skill',
            field=models.ForeignKey(help_text='被驗證的技能', on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='core.skilltemplate'),
        ),
        migrations.AlterField(
            model_name='skillverification',
            name='verdict',
            field=models.CharField(choices=[('PENDING', '待驗證'), ('PASSED', '通過 — 輸出符合預期'), ('FAILED', '失敗 — 輸出不符合預期'), ('INCONCLUSIVE', '無法確定 — Agent 無法明確判斷'), ('ERROR', '系統錯誤 — 執行過程發生異常')], default='PENDING', help_text='驗證裁決', max_length=20),
        ),
    ]
