# Generated by Django 5.2.4 on 2025-12-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_nucleiscan"),
    ]

    operations = [
        migrations.AddField(
            model_name="nucleiscan",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                db_index=True,
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
