# Generated by Django 5.2.4 on 2026-01-04 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_nucleiscan_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalurlresult",
            name="tech_stack",
        ),
        migrations.RemoveField(
            model_name="urlresult",
            name="tech_stack",
        ),
        migrations.CreateModel(
            name="TechStack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="技術名稱，如 PHP, Nginx",
                        max_length=100,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True, help_text="版本號", max_length=100, null=True
                    ),
                ),
                (
                    "categories",
                    models.JSONField(
                        default=list,
                        help_text="分類，如 ['Web servers', 'Reverse proxies']",
                    ),
                ),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "subdomain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technologies",
                        to="core.subdomain",
                    ),
                ),
                (
                    "url_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technologies",
                        to="core.urlresult",
                    ),
                ),
            ],
            options={
                "unique_together": {("url_result", "name", "version")},
            },
        ),
    ]
