# Generated by Django 5.2.8 on 2026-03-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ipaianalysis_inferred_purpose_ipaianalysis_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomainaianalysis',
            name='inferred_purpose',
            field=models.TextField(blank=True, help_text='推斷的用途 (e.g., Web Server, API Endpoint)', null=True),
        ),
        migrations.AddField(
            model_name='subdomainaianalysis',
            name='summary',
            field=models.TextField(blank=True, help_text='AI 生成的關於此資產的一句話總結', null=True),
        ),
    ]
