# Generated by Django 5.2.4 on 2026-03-22 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_subdomainaianalysis_inferred_purpose_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            UPDATE core_overview SET plan = NULL;
            UPDATE core_ipaianalysis SET potential_vulnerabilities = NULL;
            UPDATE core_subdomainaianalysis SET potential_vulnerabilities = NULL;
            UPDATE core_urlaianalysis SET potential_vulnerabilities = NULL;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.AlterUniqueTogether(
            name="techstack",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="historicalip",
            name="ipv4",
        ),
        migrations.RemoveField(
            model_name="historicalip",
            name="ipv6",
        ),
        migrations.RemoveField(
            model_name="historicalsubdomain",
            name="cname",
        ),
        migrations.RemoveField(
            model_name="historicalsubdomain",
            name="dns_records",
        ),
        migrations.RemoveField(
            model_name="ip",
            name="ipv4",
        ),
        migrations.RemoveField(
            model_name="ip",
            name="ipv6",
        ),
        migrations.RemoveField(
            model_name="step",
            name="command_template",
        ),
        migrations.RemoveField(
            model_name="step",
            name="expectation",
        ),
        migrations.RemoveField(
            model_name="step",
            name="note",
        ),
        migrations.RemoveField(
            model_name="subdomain",
            name="cname",
        ),
        migrations.RemoveField(
            model_name="subdomain",
            name="dns_records",
        ),
        migrations.RemoveField(
            model_name="verification",
            name="step",
        ),
        migrations.AddField(
            model_name="historicalip",
            name="address",
            field=models.GenericIPAddressField(
                blank=True,
                db_index=True,
                help_text="IP 位址 (IPv4 或是 IPv6)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalip",
            name="version",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(4, "IPv4"), (6, "IPv6")],
                help_text="IP 版本",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ip",
            name="address",
            field=models.GenericIPAddressField(
                blank=True,
                db_index=True,
                help_text="IP 位址 (IPv4 或是 IPv6)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ip",
            name="version",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(4, "IPv4"), (6, "IPv6")],
                help_text="IP 版本",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="parent_step",
            field=models.ForeignKey(
                blank=True,
                help_text="父步驟。為 None 表示此 Step 是 Overview 下的頂層步驟。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_steps",
                to="core.step",
            ),
        ),
        migrations.AddField(
            model_name="techstack",
            name="target",
            field=models.ForeignKey(
                blank=True,
                help_text="最高層級的聚合目標（用於繪製專案整體技術棧圖譜）",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="technologies",
                to="core.target",
            ),
        ),
        migrations.AddField(
            model_name="verification",
            name="attack_vector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verifications",
                to="core.attackvector",
            ),
        ),
        migrations.AddField(
            model_name="vulnerability",
            name="overview",
            field=models.ForeignKey(
                blank=True,
                help_text="此漏洞所屬的戰略概覽（用於報表聚合）",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_vulnerabilities",
                to="core.overview",
            ),
        ),
        migrations.AddField(
            model_name="vulnerability",
            name="source_attack_vector",
            field=models.ForeignKey(
                blank=True,
                help_text="發現此漏洞的攻擊向量（若由 AI 驗證路徑產生）",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_vulnerabilities",
                to="core.attackvector",
            ),
        ),
        migrations.AlterField(
            model_name="attackvector",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ipaianalysis",
            name="overview",
            field=models.ForeignKey(
                blank=True,
                help_text="所屬的戰略概覽 (Overview) 紀錄",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.overview",
            ),
        ),
        migrations.AlterField(
            model_name="ipaianalysis",
            name="potential_vulnerabilities",
            field=models.JSONField(
                blank=True, help_text="推斷的潛在漏洞列表", null=True
            ),
        ),
        migrations.AlterField(
            model_name="ipaianalysis",
            name="triggered_by_step",
            field=models.ForeignKey(
                blank=True,
                help_text="觸發此次分析的前置步驟 (若是初始分析則為 Null)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.step",
            ),
        ),
        migrations.AlterField(
            model_name="overview",
            name="plan",
            field=models.JSONField(
                blank=True,
                help_text="AI 擬定的結構化計畫。格式: {objectives: [{id, description, priority, status}], reasoning: str, generated_at: iso8601}",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payload",
            name="platform",
            field=models.CharField(
                choices=[
                    ("linux", "Linux"),
                    ("windows", "Windows"),
                    ("macos", "macOS"),
                    ("web", "Web (Browser)"),
                    ("universal", "Universal"),
                ],
                default="universal",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="step",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("WAITING_FOR_ASYNC", "Waiting for Async Callback"),
                    ("ENDED", "has ended"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subdomainaianalysis",
            name="overview",
            field=models.ForeignKey(
                blank=True,
                help_text="所屬的戰略概覽 (Overview) 紀錄",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.overview",
            ),
        ),
        migrations.AlterField(
            model_name="subdomainaianalysis",
            name="potential_vulnerabilities",
            field=models.JSONField(
                blank=True, help_text="推斷的潛在漏洞列表", null=True
            ),
        ),
        migrations.AlterField(
            model_name="subdomainaianalysis",
            name="tech_stack_summary",
            field=models.TextField(
                blank=True, help_text="對其技術棧的風險分析", null=True
            ),
        ),
        migrations.AlterField(
            model_name="subdomainaianalysis",
            name="triggered_by_step",
            field=models.ForeignKey(
                blank=True,
                help_text="觸發此次分析的前置步驟 (若是初始分析則為 Null)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.step",
            ),
        ),
        migrations.AlterField(
            model_name="urlaianalysis",
            name="overview",
            field=models.ForeignKey(
                blank=True,
                help_text="所屬的戰略概覽 (Overview) 紀錄",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.overview",
            ),
        ),
        migrations.AlterField(
            model_name="urlaianalysis",
            name="potential_vulnerabilities",
            field=models.JSONField(
                blank=True, help_text="推斷的潛在漏洞列表", null=True
            ),
        ),
        migrations.AlterField(
            model_name="urlaianalysis",
            name="triggered_by_step",
            field=models.ForeignKey(
                blank=True,
                help_text="觸發此次分析的前置步驟 (若是初始分析則為 Null)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.step",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerability",
            name="ip_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vulnerabilities",
                to="core.ip",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerability",
            name="subdomain_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vulnerabilities",
                to="core.subdomain",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerability",
            name="url_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vulnerabilities",
                to="core.urlresult",
            ),
        ),
        migrations.CreateModel(
            name="CommandTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("tool_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "if_system_tool",
                    models.BooleanField(
                        default=False, help_text="是否使用平臺自帶工具"
                    ),
                ),
                ("command", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attack_vector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="command_templates",
                        to="core.attackvector",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommandExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待執行"),
                            ("RUNNING", "執行中"),
                            ("SUCCESS", "成功"),
                            ("FAILED", "失敗"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "result",
                    models.TextField(blank=True, help_text="執行輸出結果", null=True),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "triggered_by_step",
                    models.ForeignKey(
                        blank=True,
                        help_text="觸發此次執行的 Step",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="command_executions",
                        to="core.step",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        help_text="執行的命令模板",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="core.commandtemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DNSRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        db_index=True,
                        help_text="DNS 紀錄類型，如 A, AAAA, CNAME, MX, TXT, NS 等",
                        max_length=15,
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        help_text="DNS 紀錄的內容，例如 IP 位址或 CNAME 目標域名"
                    ),
                ),
                (
                    "ttl",
                    models.IntegerField(
                        blank=True, help_text="Time to Live", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subdomain",
                    models.ForeignKey(
                        help_text="關聯的子域名",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dns_records",
                        to="core.subdomain",
                    ),
                ),
            ],
            options={
                "verbose_name": "DNS 解析記錄",
                "verbose_name_plural": "DNS 解析記錄",
                "unique_together": {("subdomain", "record_type", "value")},
            },
        ),
        migrations.DeleteModel(
            name="Method",
        ),
    ]
