# Generated by Django 5.2.4 on 2026-05-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_techstack_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="initialaianalysis",
            name="risk_score",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="AI 根據初始資料判斷的風險分數 (0-100)"
            ),
        ),
    ]
