# Generated by Django 5.2.8 on 2026-06-02 11:35

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_vulnerability_enrichment_attempted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cveintelligence',
            name='cwe_ids',
            field=models.JSONField(blank=True, default=list, help_text='CWE 弱點分類 ID 清單，例如 ["CWE-79", "CWE-502"]'),
        ),
        migrations.AddIndex(
            model_name='cveintelligence',
            index=django.contrib.postgres.indexes.GinIndex(fields=['affected_products'], name='cve_affected_products_gin'),
        ),
    ]
