# Generated by Django 5.2.8 on 2026-06-02 11:41

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cve_cwe_ids_and_gin_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cveintelligence',
            index=django.contrib.postgres.indexes.GinIndex(fields=['data_sources'], name='cve_data_sources_gin'),
        ),
    ]
