# Generated by Django 5.2.4 on 2026-05-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_initialaianalysis_risk_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="overview",
            name="thread_id",
            field=models.IntegerField(
                blank=True,
                help_text="筆記本 Overview 的 AI 對話 Thread ID (for push-callback)",
                null=True,
            ),
        ),
    ]
