# Generated by Django 5.2.4 on 2026-05-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_thread_id_to_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='parent_thread_id',
            field=models.IntegerField(blank=True, help_text='建立此任務的上層節點/Caller Thread ID (for async completion callback)', null=True),
        ),
    ]
