# Generated by Django 5.2.8 on 2026-06-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cve_data_sources_gin_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cveintelligence',
            name='cwe_ids',
            field=models.JSONField(blank=True, default=list, help_text='CWE 弱點分類 ID 清單，例如 ["CWE-79", "CWE-502"]', null=True),
        ),
    ]
