# Generated by Django 5.2.4 on 2026-01-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_subdomainseed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nucleiscan",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
