# Generated by Django 5.2.4 on 2026-05-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_overview_parent_thread_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overview',
            name='status',
            field=models.CharField(choices=[('PLANNING', '戰略規劃中'), ('EXECUTING', '執行任務中'), ('STALLED', '受阻/待人工'), ('COMPLETED', '已達成階段目標')], default='PLANNING', max_length=50),
        ),
        migrations.AlterField(
            model_name='step',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('WAITING_FOR_ASYNC', 'Waiting for Async Callback'), ('ENDED', 'has ended')], default='PENDING', max_length=50),
        ),
    ]
