# Generated by Django 5.2.8 on 2026-06-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cve_cwe_ids_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecompressionchunk',
            name='strategy',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RETAIN', 'Retain Full Content'), ('TEXTUALIZE', 'Textualize'), ('DISCARD', 'Discard Entirely')], default='PENDING', help_text='Agent-decided retention strategy for this chunk', max_length=20),
        ),
    ]
