# Generated by Django 5.2.4 on 2026-01-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_historicalurlresult_content_fetch_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nmapscan",
            name="which_seed",
        ),
        migrations.AddField(
            model_name="nmapscan",
            name="which_seed",
            field=models.ManyToManyField(
                blank=True, related_name="nmap_scans", to="core.seed"
            ),
        ),
    ]
