# Generated by Django 5.2.4 on 2026-05-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_overview_status_alter_step_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='技能名稱，例如 django-csrf-bypass', max_length=100, unique=True)),
                ('description', models.TextField(help_text='技能摘要描述。用於 RAG 檢索，讓 AI 判斷是否需要呼叫此技能。')),
                ('instructions', models.TextField(help_text='等同於 SKILL.md，包含該如何正確使用與傳參的指南。')),
                ('script_content', models.TextField(blank=True, help_text='實際執行的工具源碼 (例如 Python 或 Bash 腳本)。', null=True)),
                ('language', models.CharField(default='python', help_text='腳本語言', max_length=20)),
                ('tags', models.JSONField(default=list, help_text="標籤(如 'django', 'csrf', 'python') 用於分類與過濾")),
                ('usage_count', models.IntegerField(default=0, help_text='被使用的次數，幫助排序高信賴度的且被重複驗證過的技能')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill 技能',
                'verbose_name_plural': 'Skill 技能庫',
                'db_table': 'core_skill_template',
                'ordering': ['-usage_count', '-updated_at'],
            },
        ),
    ]
