# Generated by Django 5.2.4 on 2026-05-08 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_skilltemplate_alter_verification_confidence_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('curl', 'Shell/Curl Output'), ('crawler', 'Flaresolverr Crawler'), ('nuclei', 'Nuclei Report'), ('other', 'Other')], default='other', max_length=20)),
                ('source_url', models.URLField(blank=True, help_text='來源網址', null=True)),
                ('raw_content', models.TextField(help_text='完整原始內容')),
                ('content_size', models.IntegerField(default=0, help_text='字元數')),
                ('ai_summary', models.TextField(blank=True, help_text='AI 第一次存入時自動產生的大意總結，避免重複分析', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_blobs', to='core.step')),
            ],
            options={
                'verbose_name': '內容長期記憶',
                'verbose_name_plural': '內容長期記憶庫',
                'db_table': 'core_content_blob',
                'ordering': ['-created_at'],
            },
        ),
    ]
