# Generated by Django 5.2.4 on 2026-01-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_vulnerability_description_vulnerability_last_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalurlresult",
            name="cleaned_html",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="urlresult",
            name="cleaned_html",
            field=models.TextField(blank=True, null=True),
        ),
    ]
