# Generated by Django 5.2.8 on 2026-06-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_pentestheaderconfig_default_max_concurrency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='javascriptfile',
            name='is_source_map',
            field=models.BooleanField(db_index=True, default=False, help_text='此檔案是否為 JavaScript Source Map (.map)。'),
        ),
        migrations.AddField(
            model_name='javascriptfile',
            name='source_map_sources',
            field=models.JSONField(blank=True, help_text='Source Map 的 sources[] 欄位，記錄原始檔案路徑列表。', null=True),
        ),
    ]
