# Generated by Django 5.2.4 on 2026-05-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_verification_confidence_score_contentblob'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When this step transitioned to COMPLETED or FAILED. Used for execution timing.', null=True),
        ),
    ]
