# Generated by Django 5.2.4 on 2026-01-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_historicalurlresult_cleaned_html_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalurlresult",
            name="extracted_js",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="urlresult",
            name="extracted_js",
            field=models.TextField(blank=True, null=True),
        ),
    ]
