# Generated by Django 5.2.4 on 2026-05-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_step_completed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verification",
            name="confidence_score",
            field=models.PositiveSmallIntegerField(
                blank=True,
                db_column="confidence",
                help_text="AI 回傳的信心分數 (0-100)",
                null=True,
            ),
        ),
    ]
