# Generated by Django 5.2.8 on 2026-06-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_pentestheaderconfig_default_max_concurrency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amassscan',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nucleiscan',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nucleiscan',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='token_usage',
            field=models.JSONField(blank=True, help_text='Accumulated LLM token usage for this step: {prompt_tokens, completion_tokens, total_tokens}', null=True),
        ),
        migrations.AddField(
            model_name='subbrute',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subfinderscan',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amassscan',
            name='status',
            field=models.CharField(choices=[('PENDING', '待處理'), ('RUNNING', '運行中'), ('COMPLETED', '已完成'), ('FAILED', '失敗')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='nmapscan',
            name='status',
            field=models.CharField(choices=[('PENDING', '待處理'), ('RUNNING', '運行中'), ('COMPLETED', '已完成'), ('FAILED', '失敗')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='nucleiscan',
            name='status',
            field=models.CharField(choices=[('PENDING', '待處理'), ('RUNNING', '運行中'), ('COMPLETED', '已完成'), ('FAILED', '失敗')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='overview',
            name='status',
            field=models.CharField(choices=[('PLANNING', '戰略規劃中'), ('EXECUTING', '執行任務中'), ('STALLED', '受阻/待人工'), ('COMPLETED', '已達成階段目標'), ('NEEDS_GUIDANCE', '待指導/升級')], default='PLANNING', max_length=50),
        ),
        migrations.AlterField(
            model_name='subbrute',
            name='status',
            field=models.CharField(choices=[('PENDING', '待處理'), ('RUNNING', '運行中'), ('COMPLETED', '已完成'), ('FAILED', '失敗')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='subfinderscan',
            name='status',
            field=models.CharField(choices=[('PENDING', '待處理'), ('RUNNING', '運行中'), ('COMPLETED', '已完成'), ('FAILED', '失敗')], db_index=True, default='PENDING', max_length=10),
        ),
    ]
