# Generated by OpenCode on 2026-06-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_scan_record_abstract_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, max_length=128)),
                ('parent_run_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('node_name', models.CharField(blank=True, max_length=128, null=True)),
                ('tool_name', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
                ('content', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('sequence', models.BigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.thread')),
            ],
            options={
                'verbose_name': 'Thread Event',
                'verbose_name_plural': 'Thread Events',
                'db_table': 'ai_assistant_thread_event',
                'ordering': ('sequence',),
            },
        ),
        migrations.AddIndex(
            model_name='threadevent',
            index=models.Index(fields=['thread', 'sequence'], name='thread_event_thread_seq'),
        ),
        migrations.AddIndex(
            model_name='threadevent',
            index=models.Index(fields=['thread', 'created_at'], name='thread_event_thread_created'),
        ),
        migrations.AddIndex(
            model_name='threadevent',
            index=models.Index(fields=['event_type'], name='thread_event_type'),
        ),
        migrations.AddIndex(
            model_name='threadevent',
            index=models.Index(fields=['run_id'], name='thread_event_run'),
        ),
    ]
