# Generated by Django 5.2.8 on 2026-06-09 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_threadevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant_id', models.CharField(blank=True, max_length=255)),
                ('run_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('WAITING', 'Waiting'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('BLOCKED', 'Blocked')], db_index=True, default='RUNNING', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execution_graphs', to='core.thread')),
            ],
            options={
                'db_table': 'execution_graph',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='ExecutionNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('GRAPH', 'Graph'), ('LLM', 'LLM'), ('TOOL', 'Tool'), ('SCANNER', 'Scanner'), ('TASK', 'Task'), ('SYSTEM', 'System')], db_index=True, default='TASK', max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('WAITING', 'Waiting'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('SKIPPED', 'Skipped'), ('BLOCKED', 'Blocked')], db_index=True, default='PENDING', max_length=32)),
                ('tool_call_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('external_task_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('wait_reason', models.CharField(blank=True, max_length=64, null=True)),
                ('input', models.JSONField(blank=True, default=dict)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('error', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sequence', models.BigIntegerField(db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='core.executiongraph')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.executionnode')),
            ],
            options={
                'db_table': 'execution_node',
                'ordering': ('sequence', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ExecutionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=96)),
                ('status', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('content', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('sequence', models.BigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.executiongraph')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.executionnode')),
            ],
            options={
                'db_table': 'execution_event',
                'ordering': ('sequence', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ExecutionArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(db_index=True, max_length=96)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_blob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_artifacts', to='core.contentblob')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='core.executiongraph')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='core.executionnode')),
            ],
            options={
                'db_table': 'execution_artifact',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='executiongraph',
            index=models.Index(fields=['thread', 'status'], name='exec_graph_thread_status'),
        ),
        migrations.AddIndex(
            model_name='executiongraph',
            index=models.Index(models.OrderBy(models.F('started_at'), descending=True), name='exec_graph_started_desc'),
        ),
        migrations.AddIndex(
            model_name='executiongraph',
            index=models.Index(fields=['run_id'], name='exec_graph_run'),
        ),
        migrations.AddIndex(
            model_name='executionnode',
            index=models.Index(fields=['graph', 'sequence'], name='exec_node_graph_seq'),
        ),
        migrations.AddIndex(
            model_name='executionnode',
            index=models.Index(fields=['graph', 'status'], name='exec_node_graph_status'),
        ),
        migrations.AddIndex(
            model_name='executionnode',
            index=models.Index(fields=['graph', 'kind'], name='exec_node_graph_kind'),
        ),
        migrations.AddConstraint(
            model_name='executionnode',
            constraint=models.UniqueConstraint(fields=('graph', 'sequence'), name='uniq_exec_node_graph_seq'),
        ),
        migrations.AddIndex(
            model_name='executionevent',
            index=models.Index(fields=['graph', 'sequence'], name='exec_event_graph_seq'),
        ),
        migrations.AddIndex(
            model_name='executionevent',
            index=models.Index(fields=['node', 'sequence'], name='exec_event_node_seq'),
        ),
        migrations.AddIndex(
            model_name='executionevent',
            index=models.Index(fields=['event_type'], name='exec_event_type'),
        ),
        migrations.AddConstraint(
            model_name='executionevent',
            constraint=models.UniqueConstraint(fields=('graph', 'sequence'), name='uniq_exec_event_graph_seq'),
        ),
        migrations.AddIndex(
            model_name='executionartifact',
            index=models.Index(fields=['graph', 'artifact_type'], name='exec_art_graph_type'),
        ),
        migrations.AddIndex(
            model_name='executionartifact',
            index=models.Index(fields=['node', 'artifact_type'], name='exec_art_node_type'),
        ),
    ]
