# Generated by Django 5.2.8 on 2026-06-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_urlresult_dom_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='step',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='step',
            name='parent_step',
        ),
        migrations.RemoveField(
            model_name='step',
            name='subdomain',
        ),
        migrations.RemoveField(
            model_name='step',
            name='url_result',
        ),
        migrations.RemoveField(
            model_name='contentblob',
            name='step',
        ),
        migrations.RemoveField(
            model_name='commandexecution',
            name='triggered_by_step',
        ),
        migrations.RemoveField(
            model_name='attackvector',
            name='discovery_step',
        ),
        migrations.RemoveField(
            model_name='stepnote',
            name='step',
        ),
        migrations.RemoveField(
            model_name='steplog',
            name='step',
        ),
        migrations.AlterField(
            model_name='verification',
            name='execution_output',
            field=models.TextField(blank=True, help_text='實際執行輸出（用於驗證比對）', null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='observation_prompt',
            field=models.TextField(help_text='描述這次執行的成功標準，AI 會閱讀實際輸出後判斷是否達成。'),
        ),
        migrations.DeleteModel(
            name='ScriptExecution',
        ),
        migrations.DeleteModel(
            name='StepNote',
        ),
        migrations.DeleteModel(
            name='Step',
        ),
        migrations.DeleteModel(
            name='StepLog',
        ),
    ]
