# Generated by Django 5.2.8 on 2026-06-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_step_ip_remove_step_overview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalurlresult',
            name='content_fetch_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS_FETCHED', 'SUCCESS_FETCHED'), ('SUCCESS_REDIRECTED_EXTERNAL', 'SUCCESS_REDIRECTED_EXTERNAL'), ('FAILED_NO_CONTENT', 'FAILED_NO_CONTENT'), ('FAILED_NETWORK_ERROR', 'FAILED_NETWORK_ERROR'), ('FAILED_BLOCKED', 'FAILED_BLOCKED'), ('FAILED_DNS_ERROR', 'FAILED_DNS_ERROR'), ('FAILED_TIMEOUT', 'FAILED_TIMEOUT'), ('FAILED_CLIENT_ERROR', 'FAILED_CLIENT_ERROR'), ('FAILED_SERVER_ERROR', 'FAILED_SERVER_ERROR'), ('FAILED_SYSTEM_ERROR', 'FAILED_SYSTEM_ERROR')], db_index=True, default='PENDING', help_text='抓取/下載內容的狀態（成功、失敗原因、是否被導向外部…）。', max_length=30),
        ),
        migrations.AlterField(
            model_name='urlresult',
            name='content_fetch_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS_FETCHED', 'SUCCESS_FETCHED'), ('SUCCESS_REDIRECTED_EXTERNAL', 'SUCCESS_REDIRECTED_EXTERNAL'), ('FAILED_NO_CONTENT', 'FAILED_NO_CONTENT'), ('FAILED_NETWORK_ERROR', 'FAILED_NETWORK_ERROR'), ('FAILED_BLOCKED', 'FAILED_BLOCKED'), ('FAILED_DNS_ERROR', 'FAILED_DNS_ERROR'), ('FAILED_TIMEOUT', 'FAILED_TIMEOUT'), ('FAILED_CLIENT_ERROR', 'FAILED_CLIENT_ERROR'), ('FAILED_SERVER_ERROR', 'FAILED_SERVER_ERROR'), ('FAILED_SYSTEM_ERROR', 'FAILED_SYSTEM_ERROR')], db_index=True, default='PENDING', help_text='抓取/下載內容的狀態（成功、失敗原因、是否被導向外部…）。', max_length=30),
        ),
    ]
