# Generated by Django 5.2.4 on 2026-06-11 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_historicalurlresult_content_fetch_status_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="skillmergeevaluation",
            name="core_skill__skill_a_60375d_idx",
        ),
        migrations.AlterField(
            model_name="apikey",
            name="key_value",
            field=models.TextField(help_text="加密後的 API 金鑰"),
        ),
        migrations.AlterField(
            model_name="skillmergeevaluation",
            name="skill_a",
            field=models.ForeignKey(
                help_text="技能 A（ID 較小者）",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="merge_evals_as_a",
                to="core.skilltemplate",
            ),
        ),
        migrations.AlterField(
            model_name="skillmergeevaluation",
            name="skill_b",
            field=models.ForeignKey(
                help_text="技能 B（ID 較大者）",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="merge_evals_as_b",
                to="core.skilltemplate",
            ),
        ),
        migrations.AlterField(
            model_name="skilltemplate",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="技能名稱，例如 django-csrf-bypass",
                max_length=100,
            ),
        ),
    ]
