# Generated by Django 5.2.8 on 2026-06-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_skillmergeevaluation_core_skill__skill_a_60375d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblob',
            name='page_breakdown',
            field=models.JSONField(blank=True, help_text='LLM 生成的结构化页面划分（[{title, content}]），每页至多 4000 字', null=True),
        ),
    ]
