# Generated by Django 5.2.8 on 2026-06-16 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_contentblob_page_breakdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='bound_overview_id',
            field=models.ForeignKey(blank=True, db_column='bound_overview_id', help_text='The Overview this thread is currently focused on. Automatically set when binding to a target.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.overview'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='bound_target_id',
            field=models.ForeignKey(blank=True, db_column='bound_target_id', help_text='The Target this thread is currently focused on. Set by the AI agent via bind_to_target tool.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.target'),
        ),
    ]
