# Generated by Django 5.2.8 on 2026-06-18 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_vulnerability_target_pocrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='port_service',
            field=models.JSONField(blank=True, help_text='開放端口與服務快照', null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='recon_summary',
            field=models.TextField(blank=True, help_text='偵察階段摘要（子域名數量、開放端口、技術棧等高層次總結）', null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='subdomain_intel',
            field=models.JSONField(blank=True, help_text='子域名情報快照（高價值子域名、解析狀態等）', null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='tech_stack',
            field=models.JSONField(blank=True, help_text='偵測到的技術棧快照（結構化，取代 techs）', null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='vuln_intel',
            field=models.JSONField(blank=True, help_text='確認漏洞情報快照（嚴重度、位置、狀態）', null=True),
        ),
        migrations.AlterField(
            model_name='overview',
            name='techs',
            field=models.JSONField(blank=True, help_text='偵測到的技術棧（舊欄位，將逐步淘汰，改用 tech_stack）', null=True),
        ),
        migrations.CreateModel(
            name='OverviewPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('RECON_SUMMARY', '偵察摘要'), ('SUBDOMAIN_INTEL', '子域名情報'), ('PORT_SERVICE', '端口服務'), ('URL_ENDPOINT', 'URL 端點'), ('VULNERABILITY', '漏洞'), ('ATTACK_VECTOR', '攻擊向量'), ('TECH_STACK', '技術棧'), ('STRATEGIC_PLAN', '戰略計畫'), ('FREEFORM', '自由筆記')], db_index=True, help_text='情報分區類型', max_length=30)),
                ('title', models.CharField(help_text='此分區的標題（供 agent 查詢時識別）', max_length=200)),
                ('content', models.TextField(help_text='此分區的完整內容')),
                ('page_breakdown', models.JSONField(blank=True, help_text='結構化分頁（當 content 過大時由 LLM 切分）。格式: [{title: str, content: str}, ...]', null=True)),
                ('summary', models.TextField(blank=True, default='', help_text='此分區的簡短摘要（agent 快速瀏覽用）')),
                ('source_agent', models.CharField(blank=True, default='', help_text='寫入此頁的 agent 識別碼', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overview', models.ForeignKey(help_text='所屬的 Overview（1:1 綁定 Target）', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.overview')),
            ],
            options={
                'verbose_name': 'Overview 分頁',
                'verbose_name_plural': 'Overview 分頁',
                'db_table': 'core_overview_page',
                'ordering': ['section_type', '-updated_at'],
                'indexes': [models.Index(fields=['overview', 'section_type'], name='ovpage_section_idx'), models.Index(fields=['updated_at'], name='ovpage_updated_idx')],
            },
        ),
    ]
