# Generated by Django 5.2.8 on 2026-06-18 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_overview_core_fields_and_overviewpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overview',
            name='ips',
            field=models.ManyToManyField(blank=True, related_name='highlighted_in_overview', to='core.ip'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='subdomains',
            field=models.ManyToManyField(blank=True, related_name='highlighted_in_overview', to='core.subdomain'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='target',
            field=models.OneToOneField(blank=True, help_text='1:1 綁定 Target — 每個目標只有一個 Overview 作為情報中樞', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overview', to='core.target'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='url_results',
            field=models.ManyToManyField(blank=True, related_name='highlighted_in_overview', to='core.urlresult'),
        ),
    ]
