# Generated by Django 5.2.8 on 2026-06-18 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_overview_onetoone_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAgentDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatcher_agent', models.CharField(default='automation_agent', help_text='派發者 agent 識別碼', max_length=50)),
                ('sub_agent_type', models.CharField(choices=[('recon_agent', 'Recon Agent'), ('post_exploit_agent', 'Post-Exploit Agent'), ('reporting_agent', 'Reporting Agent')], help_text='子代理類型', max_length=50)),
                ('objective', models.TextField(blank=True, default='', help_text='派發時賦予子代理的任務目標')),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='RUNNING', max_length=20)),
                ('result_summary', models.TextField(blank=True, default='', help_text='子代理回報的結果摘要（notify_caller_agent 寫入）')),
                ('synthesized', models.BooleanField(db_index=True, default=False, help_text='AutomationAgent 是否已消化此回報（auto_execute_plan 喚醒後標記）')),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('dispatcher_thread', models.ForeignKey(blank=True, help_text='派發者的 Thread（通常是 AutomationAgent 的 sub_thread）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches_sent', to='core.thread')),
                ('overview', models.ForeignKey(help_text='派發此任務時所屬的 Overview', on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='core.overview')),
                ('sub_thread', models.ForeignKey(blank=True, help_text='子代理的 Thread', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches_received', to='core.thread')),
            ],
            options={
                'verbose_name': '子代理派發',
                'verbose_name_plural': '子代理派發',
                'db_table': 'core_subagent_dispatch',
                'ordering': ['-dispatched_at'],
                'indexes': [models.Index(fields=['overview', 'status'], name='subdispatch_status_idx'), models.Index(fields=['synthesized'], name='subdispatch_synth_idx')],
            },
        ),
    ]
