# Generated by Django 5.2.8 on 2026-06-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_subagent_dispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilltemplate',
            name='detailed_overview',
            field=models.TextField(blank=True, default='', help_text='大篇幅技術指引（documentation 型技能專用）。包含執行原理、檢測步驟、背景知識。'),
        ),
        migrations.AddField(
            model_name='skilltemplate',
            name='short_description',
            field=models.CharField(blank=True, default='', help_text='一行簡短說明（documentation 型技能建議填寫，供快速判斷用途）', max_length=200),
        ),
        migrations.AddField(
            model_name='skilltemplate',
            name='skill_type',
            field=models.CharField(choices=[('script', 'Script — 可執行腳本'), ('documentation', 'Documentation — AI 閱讀指引文件'), ('hybrid', 'Hybrid — 文件 + 腳本')], db_index=True, default='script', help_text='技能本質：script（可執行）/ documentation（指引文件）/ hybrid（兩者皆有）', max_length=20),
        ),
    ]
