# Generated by Django 5.2.8 on 2026-06-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_vulnerability_status_missionreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='rescue_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Watchdog 累計救援次數。到達 RESCUE_THRESHOLD_STALLED (3) 時自動轉 STALLED，到達 RESCUE_THRESHOLD_NEEDS_GUIDANCE (5) 時自動轉 NEEDS_GUIDANCE。'),
        ),
    ]
