# Generated by Django 5.2.4 on 2026-07-08 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_execution_sequence_objects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.JSONField(blank=True, default=dict, help_text='本次行動的目的（結構化）')),
                ('purpose_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', '待執行'), ('IN_PROGRESS', '執行中'), ('COMPLETED', '已完成'), ('FAILED', '失敗'), ('SKIPPED', '已跳過')], default='PENDING', max_length=20)),
                ('agent_role', models.CharField(blank=True, choices=[('RECON', '偵察 Agent'), ('PENTEST', '滲透 Agent'), ('REPORTING', '報告 Agent'), ('AUTOMATION', '自動化 Agent')], max_length=20, null=True)),
                ('result_summary', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='core.thread')),
                ('execution_graph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='core.executiongraph')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.target')),
            ],
            options={
                'verbose_name': '行動',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_detail', models.JSONField(blank=True, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_vectors', to='core.action')),
                ('attack_vector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_vectors', to='core.attackvector')),
            ],
            options={
                'verbose_name': '行動向量',
                'unique_together': {('action', 'attack_vector')},
            },
        ),
        migrations.AddField(
            model_name='action',
            name='attack_vectors',
            field=models.ManyToManyField(blank=True, related_name='actions', through='core.ActionVector', to='core.attackvector'),
        ),
        migrations.CreateModel(
            name='AssetEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_asset_type', models.CharField(choices=[('IP', 'IP 位址'), ('SUBDOMAIN', '子域名'), ('URL', 'URL 結果'), ('ENDPOINT', '端點'), ('PORT', '端口')], max_length=20)),
                ('to_asset_type', models.CharField(choices=[('IP', 'IP 位址'), ('SUBDOMAIN', '子域名'), ('URL', 'URL 結果'), ('ENDPOINT', '端點'), ('PORT', '端口')], max_length=20)),
                ('edge_type', models.CharField(choices=[('RESOLVES_TO', 'DNS 解析到'), ('HOSTS', '託管'), ('LINKS_TO', '連結到'), ('DISCOVERED_FROM', '發現自'), ('CUSTOM', '自訂')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discovered_by_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_edges', to='core.action')),
                ('from_endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edges_from', to='core.endpoint')),
                ('from_ip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edges_from', to='core.ip')),
                ('from_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edges_from', to='core.port')),
                ('from_subdomain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edges_from', to='core.subdomain')),
                ('from_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edges_from', to='core.urlresult')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_edges', to='core.target')),
                ('to_endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edges_to', to='core.endpoint')),
                ('to_ip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edges_to', to='core.ip')),
                ('to_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edges_to', to='core.port')),
                ('to_subdomain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edges_to', to='core.subdomain')),
                ('to_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edges_to', to='core.urlresult')),
            ],
            options={
                'verbose_name': '資產圖邊',
            },
        ),
        migrations.CreateModel(
            name='AssetLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('IP', 'IP 位址'), ('SUBDOMAIN', '子域名'), ('URL', 'URL 結果'), ('ENDPOINT', '端點'), ('PORT', '端口')], max_length=20)),
                ('agent_role', models.CharField(choices=[('RECON', '偵察 Agent'), ('PENTEST', '滲透 Agent'), ('REPORTING', '報告 Agent'), ('AUTOMATION', '自動化 Agent')], max_length=20)),
                ('lock_status', models.CharField(choices=[('HELD', '持有中'), ('RELEASED', '已釋放'), ('EXPIRED', '已過期')], default='HELD', max_length=20)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('endpoint_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.endpoint')),
                ('ip_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ip')),
                ('port_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.port')),
                ('subdomain_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subdomain')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_locks', to='core.target')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_locks', to='core.thread')),
                ('url_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.urlresult')),
            ],
            options={
                'verbose_name': '資產鎖',
            },
        ),
        migrations.CreateModel(
            name='AssetVectorLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('IP', 'IP 位址'), ('SUBDOMAIN', '子域名'), ('URL', 'URL 結果'), ('ENDPOINT', '端點'), ('PORT', '端口')], max_length=20)),
                ('status', models.CharField(choices=[('TARGETED', '已鎖定/未開始'), ('IN_PROGRESS', '進行中'), ('COMPLETED', '已完成'), ('FAILED', '失敗')], default='TARGETED', max_length=20)),
                ('agent_role', models.CharField(blank=True, choices=[('RECON', '偵察 Agent'), ('PENTEST', '滲透 Agent'), ('REPORTING', '報告 Agent'), ('AUTOMATION', '自動化 Agent')], max_length=20, null=True)),
                ('last_result', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_vector_links', to='core.thread')),
                ('attack_vector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_links', to='core.attackvector')),
                ('endpoint_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.endpoint')),
                ('ip_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ip')),
                ('port_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.port')),
                ('subdomain_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subdomain')),
                ('url_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.urlresult')),
            ],
            options={
                'verbose_name': '資產向量連結',
            },
        ),
        migrations.AddField(
            model_name='action',
            name='asset_links',
            field=models.ManyToManyField(blank=True, related_name='actions', to='core.assetvectorlink'),
        ),
        migrations.CreateModel(
            name='AttackPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.TextField()),
                ('scope', models.JSONField(blank=True, default=dict, help_text='模糊範圍 + 顯式資產清單。格式: {"fuzzy": {"asset_types": ["SUBDOMAIN"], "filter": "*.example.com"}, "explicit_asset_link_ids": [12, 34]}')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('ACTIVE', '執行中'), ('COMPLETED', '已完成'), ('ABANDONED', '已放棄')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_plans', to='core.attackplan')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_plans', to='core.target')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attack_plans', to='core.thread')),
            ],
            options={
                'verbose_name': '攻擊計劃',
            },
        ),
        migrations.AddField(
            model_name='action',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='core.attackplan'),
        ),
        migrations.CreateModel(
            name='WalkCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_asset_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walk_cursors_here', to='core.assetvectorlink')),
                ('pending_edges', models.ManyToManyField(blank=True, related_name='pending_for', to='core.assetedge')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='walk_cursor', to='core.attackplan')),
                ('traversed_edges', models.ManyToManyField(blank=True, related_name='walked_by', to='core.assetedge')),
            ],
            options={
                'verbose_name': '圖遍歷游標',
            },
        ),
        migrations.AddIndex(
            model_name='assetedge',
            index=models.Index(fields=['target', 'edge_type'], name='core_assete_target__cbcb44_idx'),
        ),
        migrations.AddIndex(
            model_name='assetedge',
            index=models.Index(fields=['from_asset_type', 'to_asset_type'], name='core_assete_from_as_bd57b1_idx'),
        ),
        migrations.AddIndex(
            model_name='assetlock',
            index=models.Index(fields=['asset_type', 'lock_status'], name='core_assetl_asset_t_bdd652_idx'),
        ),
        migrations.AddIndex(
            model_name='assetlock',
            index=models.Index(fields=['target', 'lock_status'], name='core_assetl_target__909ea4_idx'),
        ),
        migrations.AddIndex(
            model_name='assetvectorlink',
            index=models.Index(fields=['asset_type', 'status'], name='core_assetv_asset_t_d1a5a5_idx'),
        ),
        migrations.AddIndex(
            model_name='assetvectorlink',
            index=models.Index(fields=['agent_thread'], name='core_assetv_agent_t_7f5382_idx'),
        ),
        migrations.AddIndex(
            model_name='attackplan',
            index=models.Index(fields=['target', 'status'], name='core_attack_target__303213_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['plan', 'order'], name='core_action_plan_id_9b2bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['target', 'status'], name='core_action_target__7a5b5a_idx'),
        ),
    ]
