# Generated by Django 5.2.4 on 2026-07-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_attack_planning_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overview',
            name='plan',
        ),
        migrations.AlterField(
            model_name='attackvector',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
