# Generated by Django 5.2.4 on 2026-07-08 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_fix_flat_compressed_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='subagentdispatch',
            name='action',
            field=models.ForeignKey(blank=True, help_text='關聯的 Action（若子代理被派發來執行特定行動）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='core.action'),
        ),
    ]
