# Generated by Django 5.2.4 on 2026-07-15 03:05

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_expand_dispatch_agent_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), help_text='建立時間'),
        ),
    ]
