# Generated by Django 5.2.8 on 2026-07-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_target_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilltemplate',
            name='source_type',
            field=models.CharField(choices=[('vulnclaw', 'VulnClaw — 知識庫技能'), ('auto', 'Auto-generated — Agent 自動創建'), ('legacy', 'Legacy — 遷移前的舊格式')], db_index=True, default='vulnclaw', help_text='技能來源：vulnclaw（知識庫）/ auto（Agent自動生成）/ legacy（遷移前舊格式）', max_length=20),
        ),
        migrations.AddField(
            model_name='skilltemplate',
            name='warstory_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='War Story 結構化 metadata：target_type, scope, attack_chain[], tools_used[], outcome, lessons_learned[], severity, evidence_refs[]', null=True),
        ),
    ]
