"""
apps/auto/tools/system_api.py

⚠️  DEPRECATED ⚠️
此模組已被取代，請勿在此新增工具。

平台 API 工具現在由 `apps.auto.cai.core.api_tool_factory.build_tools_from_openapi()` 自動生成。
"""

import warnings
warnings.warn(
    "apps.auto.tools.system_api is deprecated. "
    "API tools are now auto-generated by api_tool_factory.build_tools_from_openapi(). "
    "Do not add new tools here.",
    DeprecationWarning,
    stacklevel=2,
)


import logging
import requests
import json
from typing import List, Optional, Dict, Any
from django.conf import settings
from apps.auto.cai.core.tool import function_tool

logger = logging.getLogger(__name__)

# REST API 調用的基礎 URL（本地 Django 伺服器）
API_BASE_URL = getattr(settings, "INTERNAL_API_BASE_URL", "http://127.0.0.1:8000/api")

@function_tool
def list_targets() -> str:
    """
    獲取系統中所有目標專案的列表。
    
    返回:
        目標列表的 JSON 字符串。
    """
    url = f"{API_BASE_URL}/targets/list"
    try:
        response = requests.get(url)
        response.raise_for_status()
        return json.dumps(response.json(), indent=2, ensure_ascii=False)
    except Exception as e:
        logger.error(f"List Targets 失敗: {e}")
        return f"錯誤: {str(e)}"

@function_tool
def create_target(name: str, description: Optional[str] = None) -> str:
    """
    創建一個新的目標專案。
    
    參數:
        name: 目標名稱。
        description: 目標描述。
        
    返回:
        新目標的詳細信息。
    """
    url = f"{API_BASE_URL}/targets/"
    payload = {"name": name, "description": description}
    try:
        response = requests.post(url, json=payload)
        response.raise_for_status()
        return json.dumps(response.json(), indent=2, ensure_ascii=False)
    except Exception as e:
        logger.error(f"Create Target 失敗: {e}")
        return f"錯誤: {str(e)}"

@function_tool
def list_seeds(target_id: int) -> str:
    """
    獲取指定目標下的所有掃描種子。
    
    參數:
        target_id: 目標 ID。
        
    返回:
        種子列表的 JSON 字符串。
    """
    url = f"{API_BASE_URL}/targets/{target_id}/seeds"
    try:
        response = requests.get(url)
        response.raise_for_status()
        return json.dumps(response.json(), indent=2, ensure_ascii=False)
    except Exception as e:
        logger.error(f"List Seeds 失敗: {e}")
        return f"錯誤: {str(e)}"

@function_tool
def add_seed(target_id: int, value: str, seed_type: str = "DOMAIN") -> str:
    """
    為指定目標添加掃描種子 (Domain/IP/URL)。
    
    參數:
        target_id: 目標 ID。
        value: 種子值 (e.g., example.com, 1.2.3.4, http://example.com)。
        seed_type: 種子類型 (DOMAIN, IP, URL)。
        
    返回:
        新添加種子的詳細信息。
    """
    url = f"{API_BASE_URL}/targets/{target_id}/seeds"
    payload = {"value": value, "type": seed_type}
    try:
        response = requests.post(url, json=payload)
        response.raise_for_status()
        return json.dumps(response.json(), indent=2, ensure_ascii=False)
    except Exception as e:
        logger.error(f"Add Seed 失敗: {e}")
        return f"錯誤: {str(e)}"

@function_tool
def trigger_subfinder_recon(seed_id: int, callback_step_id: Optional[int] = None) -> str:
    """
    對特定的種子 ID 觸發 Subfinder 偵察掃描。
    
    參數:
        seed_id: 種子 ID。
        callback_step_id: 回調用的 Step ID (可選)。
        
    返回:
        API 響應信息。
    """
    url = f"{API_BASE_URL}/subfinder/start_subfinder"
    payload = {"seed_id": seed_id, "callback_step_id": callback_step_id}
    try:
        response = requests.post(url, json=payload)
        response.raise_for_status()
        return json.dumps(response.json(), indent=2, ensure_ascii=False)
    except Exception as e:
        return f"錯誤: {str(e)}"

@function_tool
def trigger_nuclei_vulnerability_scan(asset_type: str, asset_ids: List[int], tags: Optional[List[str]] = None, callback_step_id: Optional[int] = None) -> str:
    """
    觸發 Nuclei 漏洞或技術掃描。
    
    參數:
        asset_type: 資產類型 ('subdomains', 'ips', 'urls', 'subs_tech', 'urls_tech')。
        asset_ids: 資料庫 ID 列表。
        tags: 選用的 Nuclei 標籤。
        callback_step_id: 回調用的 Step ID (可選)。
        
    返回:
        API 響應信息。
    """
    endpoint_map = {
        "subdomains": "/nuclei_scanner/subdomains",
        "ips": "/nuclei_scanner/ips",
        "urls": "/nuclei_scanner/urls",
        "subs_tech": "/nuclei_scanner/subs_tech",
        "urls_tech": "/nuclei_scanner/urls_tech",
    }
    
    if asset_type not in endpoint_map:
        return f"錯誤：不支持的資產類型 '{asset_type}'。"
    
    url = f"{API_BASE_URL}{endpoint_map[asset_type]}"
    payload = {"ids": asset_ids, "tags": tags or [], "callback_step_id": callback_step_id}
    try:
        response = requests.post(url, json=payload)
        response.raise_for_status()
        return json.dumps(response.json(), indent=2, ensure_ascii=False)
    except Exception as e:
        return f"錯誤: {str(e)}"

@function_tool
def trigger_nmap_scan(ip: str, seed_ids: List[int], scan_ports: str = "top-1000", callback_step_id: Optional[int] = None) -> str:
    """
    啟動 Nmap 掃描任務。
    
    參數:
        ip: 目標 IP 地址。
        seed_ids: 關聯的種子 ID 列表。
        scan_ports: 掃描端口 (e.g., '80,443', '1-1000', 'top-1000')。
        callback_step_id: 回調用的 Step ID (可選)。
        
    返回:
        掃描任務詳情。
    """
    url = f"{API_BASE_URL}/nmap/start_scan"
    payload = {
        "ip": ip,
        "seed_ids": seed_ids,
        "scan_ports": scan_ports,
        "callback_step_id": callback_step_id
    }
    try:
        response = requests.post(url, json=payload)
        response.raise_for_status()
        return json.dumps(response.json(), indent=2, ensure_ascii=False)
    except Exception as e:
        return f"錯誤: {str(e)}"

# ==========================================
# Scheduler Management (排程管理)
# ==========================================

@function_tool
def list_scheduled_tasks() -> str:
    """
    獲取系統中所有定時/週期性任務的列表。
    """
    url = f"{API_BASE_URL}/scheduler/tasks"
    try:
        response = requests.get(url)
        response.raise_for_status()
        return json.dumps(response.json(), indent=2, ensure_ascii=False)
    except Exception as e:
        return f"錯誤: {str(e)}"

@function_tool
def create_scheduled_task(name: str, task: str, every: int, period: str = "minutes", args: List[Any] = None) -> str:
    """
    創建一個新的週期性任務。
    
    參數:
        name: 任務唯一名稱。
        task: Celery 任務路徑 (e.g., 'apps.subfinder.tasks.scan_all')。
        every: 間隔數值。
        period: 單位 (seconds, minutes, hours, days)。
        args: 任務參數列表。
    """
    url = f"{API_BASE_URL}/scheduler/tasks"
    payload = {
        "name": name,
        "task": task,
        "interval": {"every": every, "period": period},
        "args": json.dumps(args or [])
    }
    try:
        response = requests.post(url, json=payload)
        response.raise_for_status()
        return json.dumps(response.json(), indent=2, ensure_ascii=False)
    except Exception as e:
        return f"錯誤: {str(e)}"

# ==========================================
# Domain & URL Discovery (域名與 URL 發現)
# ==========================================

@function_tool
def trigger_gau_url_discovery(domain_name: str, callback_step_id: Optional[int] = None) -> str:
    """
    利用 GAU (Get All URLs) 獲取一個子域名下所有的歷史 URL。
    
    參數:
        domain_name: 子域名名稱 (e.g., 'www.example.com')。
        callback_step_id: 回調用的 Step ID (可選)。
    """
    url = f"{API_BASE_URL}/get_all_url/get_all_url"
    payload = {"name": domain_name, "callback_step_id": callback_step_id}
    try:
        response = requests.post(url, json=payload)
        response.raise_for_status()
        return json.dumps(response.json(), indent=2, ensure_ascii=False)
    except Exception as e:
        return f"錯誤: {str(e)}"

@function_tool
def trigger_crawler_flaresolverr(url_to_crawl: str, seed_id: Optional[int] = None, auto_create: bool = True) -> str:
    """
    啟動 FlareSolverr 爬蟲對指定 URL 進行深度抓取。
    
    參數:
        url_to_crawl: 要抓取的網址。
        seed_id: 關聯的種子 ID (可選)。
        auto_create: 是否自動創建發現的資產。
    """
    url = f"{API_BASE_URL}/flaresolverr/start_scanner"
    payload = {"url": url_to_crawl, "seed_id": seed_id, "method": "GET", "auto_create": auto_create}
    try:
        response = requests.post(url, json=payload)
        response.raise_for_status()
        return json.dumps(response.json(), indent=2, ensure_ascii=False)
    except Exception as e:
        return f"錯誤: {str(e)}"

# ==========================================
# HTTP Tools & Others (HTTP 工具與其他)
# ==========================================

@function_tool
def trigger_endpoint_fuzzing(endpoint_id: int, cookies: Optional[str] = None) -> str:
    """
    對特定的 API 端點 (Endpoint) 進行 Fuzzing 掃描。
    
    參數:
        endpoint_id: 端點資料庫 ID。
        cookies: 帶入的 Cookie 字符串 (可選)。
    """
    url = f"{API_BASE_URL}/http_sender/fuzz"
    payload = {"id": endpoint_id, "cookies": cookies}
    try:
        response = requests.post(url, json=payload)
        response.raise_for_status()
        return json.dumps(response.json(), indent=2, ensure_ascii=False)
    except Exception as e:
        return f"錯誤: {str(e)}"
