# Generated by Django 5.2.4 on 2026-03-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        help_text="服務名稱 (例如: 'OPENAI', 'HUNTER')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "key_value",
                    models.CharField(help_text="API 金鑰的實際值", max_length=512),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="是否啟用此金鑰"),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="服務描述或備註", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "API 金鑰",
                "verbose_name_plural": "API 金鑰",
            },
        ),
    ]
