# Generated by Django 5.2.4 on 2026-05-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_keys", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="service_name",
            field=models.CharField(
                help_text="服務名稱 (例如: 'shodan', 'OPENAI', 'HUNTER' - 可重複以支援多個金鑰輪轉)",
                max_length=100,
            ),
        ),
    ]
