"""
apps/ai_assistant/api/stream_views.py

Server-Sent Events (SSE) streaming endpoint for AI assistant messages.
Unlike the standard POST endpoint which blocks until completion,
this endpoint streams tokens as they are generated by the LLM.

Endpoint: GET /api/assistant/threads/{thread_id}/messages/stream/
Query params:
  - assistant_id: str (required)
  - content: str (required) — the user's message
"""
import json
import logging
# asyncio no longer needed — using native ASGI async view
from django.http import StreamingHttpResponse
from django.views.decorators.csrf import csrf_exempt
# require_GET removed — incompatible with async views

from apps.ai_assistant.helpers.assistants import AIAssistant
from apps.core.models import Thread

logger = logging.getLogger(__name__)


def _sse_event(data: str, event: str | None = None) -> str:
    """Format a single SSE event string."""
    lines = []
    if event:
        lines.append(f"event: {event}")
    # Escape newlines within data so each logical event is on its own lines
    for line in data.split("\n"):
        lines.append(f"data: {line}")
    lines.append("")  # blank line = end of event
    lines.append("")
    return "\n".join(lines)


async def _stream_generator(thread: Thread, assistant_id: str, content: str):
    """
    Async generator that yields SSE-formatted strings.
    Wraps the assistant's `astream()` call so that any exception
    is caught and forwarded as an SSE error event instead of crashing the server.
    """
    import time
    t_start = time.monotonic()
    try:
        assistant_cls = AIAssistant.get_cls(assistant_id)
        assistant = assistant_cls(thread=thread)  # pass thread so tools can access it

        # Save the HumanMessage to DB immediately so it's not lost if stream aborts/hangs
        from asgiref.sync import sync_to_async
        from langchain_core.messages import HumanMessage
        from apps.ai_assistant.helpers.django_messages import save_django_messages
        
        await sync_to_async(save_django_messages)([HumanMessage(content=content)], thread=thread)

        # Yield a "start" event so the frontend knows streaming has begun
        yield _sse_event(json.dumps({"status": "started"}), event="start")

        # Stream tokens from the LangGraph graph
        async for chunk in assistant.astream(content, thread=thread):
            if chunk:
                # chunk is a str token from the agent "agent" node
                yield _sse_event(chunk)

        # Send timing stats before done
        elapsed_ms = int((time.monotonic() - t_start) * 1000)
        yield _sse_event(json.dumps({"elapsed_ms": elapsed_ms}), event="stats")

        # Signal successful completion
        yield _sse_event("[DONE]", event="done")

    except Exception as exc:
        logger.error(
            "[SSE stream_thread_message] Exception during stream "
            f"for thread_id={thread.id}: {type(exc).__name__}: {exc}",
            exc_info=True,
        )
        elapsed_ms = int((time.monotonic() - t_start) * 1000)
        yield _sse_event(json.dumps({"elapsed_ms": elapsed_ms}), event="stats")
        error_payload = json.dumps({"error": str(exc), "type": type(exc).__name__})
        yield _sse_event(error_payload, event="error")
        # Always send done so the client EventSource can clean up
        yield _sse_event("[DONE]", event="done")



@csrf_exempt
async def stream_thread_message(request, thread_id):
    """
    ASGI SSE endpoint: GET /api/assistant/threads/<thread_id>/messages/stream/

    Query params:
      - assistant_id: str
      - content: str
    """
    assistant_id = request.GET.get("assistant_id", "hacker_assistant_agent")  # ✅ 有 fallback
    content = request.GET.get("content", "")

    if not content:
        async def error_gen():
            yield _sse_event(json.dumps({"error": "content param is required"}), event="error")
            yield _sse_event("[DONE]", event="done")
        return _make_sse_response(error_gen())

    try:
        thread = await Thread.objects.aget(id=thread_id)  # ✅ async ORM
    except Thread.DoesNotExist:
        async def error_gen():
            yield _sse_event(json.dumps({"error": f"Thread {thread_id} not found"}), event="error")
            yield _sse_event("[DONE]", event="done")
        return _make_sse_response(error_gen())

    return _make_sse_response(_stream_generator(thread, assistant_id, content))


def _make_sse_response(generator):
    response = StreamingHttpResponse(generator, content_type="text/event-stream")
    response["Cache-Control"] = "no-cache"
    response["X-Accel-Buffering"] = "no"
    response["Access-Control-Allow-Origin"] = "*"
    return response