# Generated by Django 5.2.4 on 2026-05-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0006_thread_assistant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='bound_target_id',
            field=models.IntegerField(blank=True, help_text='The Target ID this thread is currently focused on. Set by the AI agent via bind_to_target tool.', null=True),
        ),
    ]
