# Generated by Django 5.2.8 on 2026-05-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0008_add_compression_models'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='ai_assistant_message_thread_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='ai_assistant_message_compression_idx',
        ),
        migrations.AlterField(
            model_name='globalcontextoverview',
            name='attempted_exploits',
            field=models.JSONField(default=list, help_text='Past exploits attempted: [{tool, target, result, timestamp}]'),
        ),
        migrations.AlterField(
            model_name='globalcontextoverview',
            name='confirmed_vulnerabilities',
            field=models.JSONField(default=list, help_text='List of confirmed vulnerabilities: [{title, cve, severity, location}]'),
        ),
        migrations.AlterField(
            model_name='globalcontextoverview',
            name='critical_artifacts',
            field=models.JSONField(default=list, help_text='Important artifacts to retain: [{type, value_hash, location, importance}]'),
        ),
        migrations.AlterField(
            model_name='globalcontextoverview',
            name='excluded_paths',
            field=models.JSONField(default=list, help_text='Attack vectors ruled out: [{path, reason, timestamp}]'),
        ),
        migrations.AlterField(
            model_name='globalcontextoverview',
            name='metrics',
            field=models.JSONField(default=dict, help_text='Metrics: {hosts_discovered, ports_found, services_identified, exploits_successful}'),
        ),
        migrations.AlterField(
            model_name='messagecompressionchunk',
            name='compression_ratio',
            field=models.FloatField(default=0.0, help_text='Compression ratio: (1 - compressed_size/original_size) * 100'),
        ),
        migrations.AlterField(
            model_name='threadcompressionstate',
            name='compression_summary',
            field=models.JSONField(default=dict, help_text='Metadata about compression operations: {compression_count, chunks_count, last_overview_update}'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(models.F('thread'), name='message_thread'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(models.F('compression_applied'), name='message_compression_applied'),
        ),
    ]
