# Generated by Django 5.2.8 on 2026-05-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0009_remove_message_ai_assistant_message_thread_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='If True, this thread is internal/ephemeral and hidden from the main chat list.'),
        ),
    ]
