# Generated by Django 5.2.8 on 2026-05-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0010_thread_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('human', 'Human'), ('ai', 'AI'), ('tool_call', 'Tool Call'), ('tool_result', 'Tool Result'), ('system', 'System')], default='ai', help_text='The role/type of the message (human, ai, tool_call, tool_result, system)', max_length=20),
        ),
        migrations.AddField(
            model_name='thread',
            name='bound_overview_id',
            field=models.IntegerField(blank=True, help_text='The Overview ID this thread is currently focused on. Automatically set when binding to a target.', null=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(models.F('role'), name='message_role'),
        ),
    ]
